### ISSUE TITLE
Unable to add .srt file

### ISSUE THREAD

**Issue by rafaelg1402** [donmelton/other_video_transcoding#1]
I have tried the add-subtitle param to add my .srt file but no luck. I'm assuming add-subtitle is just for subtitle already in video file. If so, would it be possible to add an option to .srt files like in Video-transcoding? Thank you :smile:

**Comment by donmelton** [comment]
@rafaelg1402 Congratulations on opening the first issue on this project! And thanks for using my software!

OK, while it's possible to add support in `other-transcode` for including external subtitle files, I really don't want to do that. And I have several reasons:

* FFmpeg converts text-based subtitles to ASS format on inclusion. ASS format is much larger and often specifies counter-productive information like which font to use when displaying the subtitle. HandBrake, which uses the FFmpeg code, does the same thing and I know from issues opened against `transcode-video` that users do not want their subtitles converted to ASS format.

* While it's possible to have `other-transcode` call `mkverge` to include text-based subtitles and avoid such conversion, doing so would add another tool dependency (which I don't want to do) and would not work when output to MP4 format (via the `--mp4` option) is required. That problem would likely require yet another external MP4-specific tool dependency to solve.

* Including an external subtitle within the video file container is not actually necessary for playback of that subtitle. Provided the subtitle is named properly, media servers such as Plex and Kodi or standalone players like VLC and `mpv` will either automatically use or at least load that subtitle providing it as an option.

I'll leave this issue open for now to allow you and others to comment.

**Comment by rafaelg1402** [comment]
Hi @donmelton Thank you for the follow up, I am actually using Kodi and i had completely forgot to check docs on how they handle subs so thank you for mentioning that it can handle it without you encoding it with the MKV file. I agree with you that it wouldn't be a positive to have to call other tools for adding external files.

**Comment by donmelton** [comment]
@rafaelg1402 OK, since no one else has added a comment and since you essentially agree with my rationale, I'll close this now.
