### ISSUE TITLE
My 720p source isn't correctly detelecined using the --detelecine option

### ISSUE THREAD

**Issue by loshlee** [donmelton/other_video_transcoding#101]
The ffmpeg construct for detelecine works great for my 1080i sources, but doesn't produce correctly detelecined output for my 720p telecined content. The ffmpeg method employed by other-transcode is "-filter:v fieldmatch\\=order\\=tff:combmatch\\=none,decimate". The method that seems to work best for my 720p telecined source is "-filter:v interlace,fieldmatch=order=tff:combmatch=full,yadif=deint=interlaced,decimate". This actually forces interlacing before using fieldmatch then yadif to detelecine and deinterlace. Here's an [example](https://www.dropbox.com/s/ufgy3sokfwxtv88/PrometheusClip.mp4?dl=0).

**Comment by donmelton** [comment]
@loshlee Interesting. Is that the source? Because I don't see a big need to deinterlace or detelecine that.

**Comment by loshlee** [comment]
Yes, that's the source. If you convert it without detelecine (even at high bitrate) and step frame by frame, you should be able to see the need. I can see a big difference even without stepping frame by frame.

**Comment by loshlee** [comment]
I can get very good results with 3000k bitrate specified if I use the detelecine method I included in my opening issue description (interlacing before using fieldmatch then yadif to detelecine and deinterlace). I was hoping you might be able to offer refinement(s).

**Comment by loshlee** [comment]
Here's my full ffmpeg command:
/usr/local/bin/ffmpeg -y -i '[path to PrometheusClip.mp4]' -filter:v interlace,fieldmatch=order=tff:combmatch=full,yadif=deint=interlaced,decimate,crop=1264:528:6:98 -c:v h264_videotoolbox -b:v 3000k -color_primaries:v bt709 -color_trc:v bt709 -colorspace:v bt709 -c:a copy '[path to PrometheusClip.detelecine.m4v]'

**Comment by donmelton** [comment]
@loshlee Thanks. I'll try that later today or tomorrow.

**Comment by loshlee** [comment]
Great! Thanks! To do frame by frame in IINA, press the .(period) key.

**Comment by loshlee** [comment]
Did you try it?

**Comment by donmelton** [comment]
@loshlee I'm looking at it now. Loooong day. But stay tuned...

**Comment by donmelton** [comment]
@loshlee The source has a frame rate of 59.940 FPS but it's progressive. Where did you get this?

**Comment by donmelton** [comment]
@loshlee BTW, the source does not play without problems even using `mpv`.

**Comment by loshlee** [comment]
For me it appears to play correctly using IINA or VLC. It's also played correctly in my Mojave Safari browser window (Version 14.0.3 (14610.4.3.1.6). It's captured from a device called the HD Fury Pro that converts HDMI to Component and S/PDIF, which I then capture using my old Hauppauge HDPVR.

**Comment by donmelton** [comment]
@loshlee By problems I mean that it has some "judder" even when played using `mpv`. And when I transcode it without using any filters, it looks and behaves exactly the same. Which is not surprising since the video is progressive and not interlaced.

I suspect that your Hauppauge HDPVR is capturing it "accurately." Meaning that it's capturing the flaws during playback.

Since the source video is technically progressive, there's not really any benefit to detelecining it. In fact, that's not really possible. I suppose deinterlacing or other filters might improve it somewhat.

I'm not sure what to suggest at this point because source files like this are always going to be an edge case. I don't really want to add more filters or filter options for this. Sorry. My only suggestion might be to continue what you're doing now with custom `ffmpeg` commands.

**Comment by loshlee** [comment]
OK. Interesting. I normally view clips like this in IINA, but it seems to me that VLC played this one better than either IINA or mpv. What's more surprising, though, is that whatever player I use, it never looks exactly the same twice if I play it repeatedly. But what convinced me to detelecine was using the frame by frame feature in IINA (similar to MPlayer OS Extended, which I still use with Jubler to edit subtitles), and seeing the 3+2 pattern. That pattern (or some other irregular pattern) remains unless I apply the detelecine method I provided. Anyway, nothing major involved here, it's just one of my methods for home time-shifted viewing. Thanks for looking into it!

**Comment by donmelton** [comment]
@loshlee No problem. I'll close this now but don't be shy if you have another issue.
