### ISSUE TITLE
No HEVC HW acceleration on Mac

### ISSUE THREAD

**Issue by Stooovie** [donmelton/other_video_transcoding#104]
HEVC encode only runs on CPU. If I understand correctly, only VT is available on Macs (I ran 'ffmpeg -hwaccels' and it returned "videotoolbox"). This is on both my 2015 5k iMac (i5 6600 and Radeon M395x) and a Hackintosh (AMD RX580 and i9 10850k, both on Big Sur 11.2.2). All typical GUI encoders such as Handbrake, AME and FFWorks encode properly even with HEVC, using Quicksync, everything seems to work.

**H264 with VT works as expected.**

When trying to run `other-transcode --hevc --vt {path}`, I get 

`Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Getting muxer capabilities...
Scanning media...
duration = 00:01:59.92
Stream mapping:
 1 = hevc_videotoolbox / 4000 Kbps
 0 = aac_at / 256 Kbps
Command line:
ffmpeg -loglevel error -stats -i /Users/stooovie/Desktop/encoding\ benchmark/2m\ -\ Original\ Prores.mov -map 0:1 -c:v hevc_videotoolbox -b:v 4000k -color_primaries:v bt709 -color_trc:v bt709 -colorspace:v bt709 -metadata:s:v title\= -disposition:v default -map 0:0 -c:a:0 aac_at -aac_at_mode:a:0 cvbr -b:a:0 256k -metadata:s:a:0 title\= -disposition:a:0 default -sn -metadata:g title\= -default_mode passthrough 2m\ -\ Original\ Prores.mkv
Transcoding...
[hevc_videotoolbox @ 0x7fec24018800] Error encoding frame: -12912
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
/usr/local/bin/other-transcode: transcoding failed: 2m - Original Prores.mkv`

Can it be a ffmpeg mismatch or something along these lines? I'm using a version of ffmpeg that, according to FFWorks' diagnostics, supports all H264 and H265 variants.

**I'm asking if HEVC with VT is something that's generally expected to work on a 10th gen i9 and a 2017 AMD GPU, or 2015-era iMacs with dGPU.**

Thanks!

EDIT: I looked at what FFWorks is calling and there's this: `-c:v hevc_videotoolbox`. Here's the entire command:

`/Users/stooovie/Library/Application\ Support/FFmpegTools/ffmpeg\ gpu  -probesize 50M -analyzeduration 100M -i /Users/stooovie/Desktop/encoding\ benchmark/2m\ \-\ Original\ Prores.mov -map 0:1 -map 0:0 -c:a aac_at -ab 320k -strict -2 -async 1 -c:v hevc_videotoolbox -b:v 9123.84k -maxrate 18247.68k -bufsize 18247.68k -r 25 -s 1920x1080 -aspect 16:9 -pix_fmt yuv420p -color_primaries bt709 -color_trc bt709 -colorspace bt709 -sc_threshold 40 -keyint_min 25 -g 250 -qmin 3 -qmax 51 -threads 16 -tag:v hvc1 -metadata creation_time=now -sn -y /Users/stooovie/Desktop/encoding\ benchmark/2m\ \-\ Original\ Prores_H264\ Main\ Profile\ \[.mp4\]_H265.mp4`

This is, indeed, running on the iGPU.

**Comment by donmelton** [comment]
@Stooovie Including `-c:v hevc_videotoolbox` on your `ffmpeg` command line does not necessarily mean that a hardware encoder is used. This is because VideoToolbox can decide to use a software encoder instead. Why and when it does this is neither clear nor predictable. This is not a problem with `ffmpeg`. This is just the way macOS works. And it's also why I recommend using a Nvidia GPU on Windows as the preferred hardware transcoding configuration.

Does that answer your question?

**Comment by Stooovie** [comment]
Okay, thanks for your answer. How does ffworks enforce it then? BTW I tried the same command `other-transcode --hevc --{PATH}` on my M1 Air and it works. It seems really unpredictable.

**Comment by donmelton** [comment]
@Stooovie I have no idea how and even _if_ the ffWorks app is enforcing that. I've never used that app. As near as I can tell, the behavior of VideoToolbox is effectively random. Sorry about that.
