### ISSUE TITLE
How do I leave original alone (don't move to trash) after transcode?

### ISSUE THREAD

**Issue by loshlee** [donmelton/other_video_transcoding#110]
I'm sure I'm not reading everything, but I can't find the option to retain the original after transcoding in version 9. Thanks.

**Comment by ttyS0** [comment]
`other-transcode` doesn't delete anything, so there doesn't need to be an option to retain the original. 😎 

If you're finding your original source is gone after a transcode, then perhaps you're using a custom wrapper script?

**Comment by loshlee** [comment]
Tried the same again and the original wasn't deleted. Must've made a mistaken observation. I'll close. Sorry, thanks.
