### ISSUE TITLE
Installing older MKVToolNix-53.0.0 for Mojave? 

### ISSUE THREAD

**Issue by coreygreenberg** [donmelton/other_video_transcoding#116]
Can anyone tell me how to get Homebrew to install MKVToolNix-53.0.0 rather than simply report that I can't install MKVToolNix at all because the latest version requires Catalina? 

For many reasons, this particular Mac I use for a Plex server and Meltonian transcoder is standing pat at Mojave, and Don's scripts have worked great until just now, when I tried updating brew and somehow MKVToolNix lost the ability to work at all. 

Uninstalling Homebrew and starting over again didn't help. Now I can't install MKVToolNix at all, so other-transcode is a no-go.

I tried Googling the issue but came up dry. Does anyone here know how to get Homebrew to install an earlier MKVToolNix, or barring that, how I can manually install 53.0.0 and get other-transcoding again? 

Thank you!

**Comment by donmelton** [comment]
@coreygreenberg Woof. I don't think I have ever actually downgraded a Homebrew formula installation. Doing a little Web search myself, I found this:

https://flaviocopes.com/homebrew-install-older-version/

Does that work for you?

**Comment by wintervaler** [comment]
Hi @coreygreenberg, in my Homebrew-loving heart I truly hope you find a solution that allows you to keep using `brew` for this. But in my lazy heart, I'm thinking that my solution would probably be to used one of the downloadable binaries of MKVToolNix from the project's website. From the looks of it, you'll need version 42.0.0 or older to be able to use it on your Mojave Mac. You can download all versions from this link: https://mkvtoolnix.download/macos/. (And maybe this goes without saying, but I'm guessing you should probably remove the Homebrew formula/cask after installing the correct version and before firing up another transcode job). 

Good luck!

**Comment by donmelton** [comment]
@wintervaler Thanks! 👍

**Comment by coreygreenberg** [comment]
Thanks hive mind! I deeply appreciate all the guidance given.

Ultimately what _seemed_ to work was simply installing the MKVToolNix-53.0.0.dmg MacOS binary and then copying the command line files to /usr/local/bin. Inartful? Inelegant? Not Homebrewed (Awaybrewed?)? I am of course ashamed but also relieved that Don’s script is working again. 

Just FYI, I too cringe when I see guys running Tiger because “it’s the last good OSX” so I forgive anyone for wishing me ill because I’m still running Mojave. I just had too many issues with Catalina, didn’t see the point of Big Sur, and I tend to leave servers alone if they’re working fine. This is the first time I’ve run into an issue where a must-have app broke because a contingent part left Mojave in the dust. But all seems well again, and I thank everyone for their help.

**Comment by ttyS0** [comment]
@coreygreenberg 

One quick suggestion. Don't copy to `/usr/local/bin`, instead symlink to there. 

```
❯ ls -l /usr/local/bin/mkv*
lrwxr-xr-x 54 sean 28 Apr  2019 /usr/local/bin/mkvextract -> /Applications/MKVToolNix.app/Contents/MacOS/mkvextract
lrwxr-xr-x 51 sean 28 Apr  2019 /usr/local/bin/mkvinfo -> /Applications/MKVToolNix.app/Contents/MacOS/mkvinfo
lrwxr-xr-x 52 sean 28 Apr  2019 /usr/local/bin/mkvmerge -> /Applications/MKVToolNix.app/Contents/MacOS/mkvmerge
lrwxr-xr-x 55 sean 28 Apr  2019 /usr/local/bin/mkvpropedit -> /Applications/MKVToolNix.app/Contents/MacOS/mkvpropedit
```

**Comment by coreygreenberg** [comment]
Thanks @ttyS0, any reason why symlinks would be better? Don's other-transcode script seems to be working fine again just having the binaries in /usr/local/bin, but yes, originally there were symlinks there instead.

**Comment by ttyS0** [comment]
@coreygreenberg 

The reason symlinks are better is because if you ever update the `MKVToolNix` application, the copied binaries will be out of date. If they are symlinks then they will always reference the version that you have installed in `/Applications/MKVToolNix`. 😄

**Comment by coreygreenberg** [comment]
Ah yes, that makes sense. From the looks of things, 53.0.0 is the last version that will work with Mojave, but it would be nice to be able to keep up with Homebrew updates without breaking Don's scripts. Although after this I don't know if I'll ever brew update again oh what am I saying of course I will. Like I have control over that.

**Comment by ttyS0** [comment]
Oh, and one more thing .... you can also pin a Homebrew package with `brew pin package@version`

So, if I wanted to make sure that `git` stayed at version `2.33.0`, I could do `brew pin git@2.33.0`.

Just mentioning it in case there are other Homebrew packages that you might want to not have upgraded, and you still want to be able to do a `brew upgrade` without spending an afternoon chasing down problems. 😄

**Comment by coreygreenberg** [comment]
Thank you Sean! Symlinking (for the first time) as we speak. Cheers and thank you all who helped me fix this.

**Comment by donmelton** [comment]
@coreygreenberg I'm glad it all worked out. My thanks, again, to @wintervaler and @ttyS0!

I'll close this now but don't be shy around here. :)
