### ISSUE TITLE
Error passing brackets to the --x265-params option

### ISSUE THREAD

**Issue by martinpickett** [donmelton/other_video_transcoding#119]
If you pass a KEY:VALUE pair with `--x265-params` where the VALUE contains brackets, `other-transcode` throws an error "/usr/local/lib/ruby/gems/3.0.0/bin/other-transcode: invalid argument:".

Luckily the fix seems simple, inserting just four characters to line 846 solves my problem. The offending line checks the validity of KEY:VALUE pairs with a regular expression, changing the expression slightly to allow brackets is all that is required. What I did, with a bit of context, is as follows.

Current:
```
opts.on '--x265-params ARG' do |arg|
    arg.split ':' do |param|
        fail UsageError, "invalid argument: #{arg}" unless param =~ /^[\w\-]+=[\w\-\.,]+$/
    end
```
New:
```
opts.on '--x265-params ARG' do |arg|
    arg.split ':' do |param|
        fail UsageError, "invalid argument: #{arg}" unless param =~ /^[\w\-]+=[\w\-\(\)\.,]+$/
    end
```

The four magical characters are `\(\)` inserted into the second half of the regular expression.

I am sure there are other ways to fix this issue so please do what you like, but without brackets, no one can do HDR10 encoding with `other-transcode`.

**Comment by donmelton** [comment]
@martinpickett Thanks for opening this! And finding and fixing the bug. :)

**Comment by donmelton** [comment]
The fix (slightly different) is checked in now.
