### ISSUE TITLE
Can't get to first base because of MKV input file requirement 

### ISSUE THREAD

**Issue by muesic** [donmelton/other_video_transcoding#139]
I have thousands of *.dvdmedia main movie rips made via MacDVDRipper Pro (MDRP). Those files are essentially just standard DVD VOB structures. I can compress these in HandBrake, however I think I like your compression tools better :-). The issue is that HandBrake can natively accept these VOB structures and compress them without issue, but in order to use other_video_transcoding I need to first go through an annoying VOB to MKV transcode. I tried MKVToolnix but it yields a really high percentage of MKV files with audio/video sync issues (the author knows about it but has said all VOB development ceased eons ago). I also tried MakeMKV and, while much better, it still has audio/video sync issues. I don't know of any other software on the Mac that can transcode VOB to MKV. As a result, I can't use other_video_transcoding :-(

For a given other-transcode command line, is there an equivalent set of options I can transplant into HandBrake so that I can compress my 20TB of VOB rips?

**Comment by donmelton** [comment]
@muesic Sorry to hear that but thank you for liking my tools.

The DVD directory structure format with its VOB and other indexes has become an obsolete format. You're correct that HandBrake is one of the few tools that still support them. VLC, for playback only, is another.

I don't really know what an equivalent set of options might be since I no longer use HandBrake.

Which video and audio encoders were you planning on using? Because the ratecontrol formulas in `other-transcode` are tailored for particular encoders.

**Comment by muesic** [comment]
For the video encoder I'm planning on x265, and I'm just doing a pass-thru on the best audio track (5.1 if available, else stereo/mono).

**Comment by muesic** [comment]
Also (and this doesn't have anything to do with this thread) I sent you an email on 2/2 but you never responded. I was wondering if "me" at your domain_name dot com was correct (I got that from your website somewhere)

**Comment by donmelton** [comment]
@muesic My apologies for not responding to your email. Things were a bit hectic at home that week and I simply forgot.

I don't actually do anything special for the `x265` encoder other than choose a target bitrate and set the VBV to default values. I thought you were using a hardware encoder which is really what `other-transcode` was designed for.

So, I recommend you just pick one of the default presets in HandBrake and use that. For `x265` it will probably work just as well.

I hope that helps.

**Comment by muesic** [comment]
OK - thanks anyway. I guess I'll just run with HandBrake then.

**Comment by donmelton** [comment]
@muesic No problem. It never hurts to ask.
