### ISSUE TITLE
invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by joeblack2k** [donmelton/other_video_transcoding#145]
Running the batch file spits out this error:

batch.rb:10:in `match': invalid byte sequence in UTF-8 (ArgumentError)

i'm running Windows 11 and using the powershell (but cmd also gives the error) 

any idea whats going on?

**Comment by joeblack2k** [comment]
this line generated a ANSI file:

Get-ChildItem -Recurse -Include *.mkv | Select-Object -ExpandProperty FullName | Set-Content queue.txt

open queue.txt and save it as a utf-8 file fixes it

**Comment by samhutchins** [comment]
Urgh, encoding always gets me. Sorry about that, glad you figured it out

**Comment by donmelton** [comment]
@joeblack2k Using `-encoding oem` with something like `out-file` in PowerShell will select UTF-8 encoding.
