### ISSUE TITLE
Unrecognized option 'default_mode'. Error splitting the argument list: Option not found

### ISSUE THREAD

**Issue by musso-joseph** [donmelton/other_video_transcoding#152]
I updated other-transcode today on my Windows 10 PC for the first time in several years. I had been transcoding some video files earlier with success, but after the update I receive the error above. In fact, the error is happening with a TV series I ripped from Bluray earlier and transcoded without problems. 

I've tried renaming the source files several times to no avail. I am calling the transcode with the following arguments:

`other-transcode --add-audio all --add-subtitle all [video file name in quotations]`

**Comment by ttyS0** [comment]
Just as a sanity check question, did you also update `ffmpeg`? I think there are options in the newest `other-transcode` that might need `ffmpeg` version 5.X. 

(on a side note, it looks like v5.0.1 was just released a couple days ago)

**Comment by musso-joseph** [comment]
> 

Updating ffmpeg and moving the executables to c:\bin seems to have fixed the issue -thanks!
