### ISSUE TITLE
add external subtitle

### ISSUE THREAD

**Issue by rnpasinos** [donmelton/other_video_transcoding#154]
how do i include external subtitles (srt, idx/sub, etc.)?

**Comment by ttyS0** [comment]
I'm pretty sure merging in an external subtitle file would be considered outside the scope of `other-transcode`, as it assumes any subtitles are already embedded into the source file. You can, however, use `MKVToolNix` merge in an external subtitle. If you do that first with the source file, you can then instruct `other-transcode` to include it in the transcode.

While I've never personally done this, the following instructions seem straight forward:

https://www.easytechguides.com/merge-subtitles-with-mkv/

**Comment by donmelton** [comment]
My thanks to @ttyS0 for that excellent comment and suggestion!

@rnpasinos Does that answer your question?

**Comment by rnpasinos** [comment]
got it! what @ttyS0 commented is what i'm actually doing, but using MKVToolNix Batch Tool instead as it's more convenient for multiple videos and subtitles. i was just wondering if there is an argument for external subs to "skip" that step. thanks!
