### ISSUE TITLE
--dry-run request 

### ISSUE THREAD

**Issue by muesic** [donmelton/other_video_transcoding#159]
When I run the --dry-run option on my uncompressed MKV files I end up seeing many things like:

-metadata:s:v title\= 
and
-metadata:s:a:0 title\= 
and 
-metadata:g title\= 

i.e. there is no title info (and I understand that's because the info is likely missing in my source file). Can I safely just omit those parts from the ffmpeg command line? 
If so then I guess I have a petty request - if there is no info on the right side of the equals sign then could you please suppress outputting that option to the ffmpeg --dry-run command line (to keep things simpler and easier to read/digest). Just trying to reduce some entropy in the universe :-)

**Comment by donmelton** [comment]
@muesic Sure, you _can_ do that. But I wouldn't recommended it.

**Comment by samhutchins** [comment]
@donmelton Why would removing those bits of the command be a problem?

**Comment by donmelton** [comment]
@samhutchins Because it's an effort for no benefit to the actual output and if you get in the habit of doing that then you might have a stray input sometime where it does matter. That's why I wouldn't recommend it.
