### ISSUE TITLE
Unrecognized option 'default_mode'

### ISSUE THREAD

**Issue by Neoakb** [donmelton/other_video_transcoding#162]
```
Command line:
ffmpeg -loglevel error -stats -i Game.of.Thrones.S01.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR/Game.of.Thrones.S01E01.Winter.Is.Coming.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR.mkv -map 0:0 -c:v libx265 -pix_fmt:v yuv420p10le -b:v 8000k -maxrate:v 25000k -bufsize:v 25000k -color_primaries:v bt2020 -color_trc:v smpte2084 -colorspace:v bt2020nc -metadata:s:v title\= -disposition:v default -map 0:1 -c:a:0 eac3 -metadata:s:a:0 title\= -disposition:a:0 default -sn -metadata:g title\= -default_mode passthrough Game.of.Thrones.S01E01.Winter.Is.Coming.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR.mkv
Transcoding...
Unrecognized option 'default_mode'.
Error splitting the argument list: Option not found

```

**Comment by ttyS0** [comment]
There isn't a lot to go on there. The version of `ffmpeg` would be useful. If you're not using version 5.X, that could be the problem. This was the case in https://github.com/donmelton/other_video_transcoding/issues/152

**Comment by donmelton** [comment]
@Neoakb I believe @ttyS0 is correct. The only way you get that error is by using an old version of `ffmpeg`, probably a few years old actually. Please upgrade to the latest `ffmpeg` and try again.

**Comment by Neoakb** [comment]
That worked, thanks!

**Comment by donmelton** [comment]
@Neoakb Excellent! As always, my thanks to @ttyS0 for handling the issue while I was away.

I'll close this now.
