### ISSUE TITLE
Allow specification of an output path other than current working directory.

### ISSUE THREAD

**Issue by hjk321** [donmelton/other_video_transcoding#164]
Currently, this tool just spits out your file in your current working directory which is nice and all but rather limiting. It would be useful for those of us using this tool to batch-convert multiple files, to be able to specify a relative or absolute path in which to place the transcoded file. Perhaps some kind of `--output-path` option?

**Comment by donmelton** [comment]
@hjk321 Thank you for using my tools!

This feature request has been made several times. The first in:

https://github.com/donmelton/other_video_transcoding/issues/9

And I think the most recent in:

https://github.com/donmelton/other_video_transcoding/issues/100

I'll repeat here what I said the last time:

> This behavior is intentional and by design. And I have no plans to change that. You can already decide where your output will go simply by using the `cd` command to change the current working directory before you invoke `other-transcode`. So it's not a limitation either.

Did you have any other questions?

**Comment by hjk321** [comment]
Fair enough.
