### ISSUE TITLE
LFE Track is removed from output

### ISSUE THREAD

**Issue by ste2w** [donmelton/other_video_transcoding#167]
so i have a question ive noticed that some files i have run through other_video_transcoding that have 7.1 or even 5.1 surround after i process them the lfe track is removed and Media Info reports that it has 5 channels after finishing instead of 6 and the files that were produced from makemkv show 5,1 or 7.1 flac and i apologize if i haven't made myself clear but is it something that ive done wrong cause my command line is  (other-transcode --hevc --eac3 "Path to movie" ) or is it a bug in the new version im not trying to sound rude or anything i haven't had this happen before i'm  just curious have a great day and i hope that i explained it clearly enough :)

**Comment by ste2w** [comment]
[free.mkv.log](https://github.com/donmelton/other_video_transcoding/files/9760685/free.mkv.log)
[midway.mkv.log](https://github.com/donmelton/other_video_transcoding/files/9760687/midway.mkv.log)

is this the right stuff? I've never done this before so i hope it is if not i can run the encode again if there is something im missing let me know what I'm missing thanks!

**Comment by donmelton** [comment]
@ste2w Yes, that's the right stuff.

Your `.log` files show that you're using `ffmpeg version N-108460-g5c94b6694a-20221002`. Where did you get that? Is that a nightly/developer build? If so, can you please use a released version instead?

**Comment by ste2w** [comment]
i oownloaded it from the ffmoeg website under the windows build whatever the latest version was is it not what they said?? im confused lol that was supposed to be the latest released build

**Comment by ste2w** [comment]
but yeah i will try and find a released build and try it again :)

**Comment by ste2w** [comment]
[free.mkv.log](https://github.com/donmelton/other_video_transcoding/files/9761157/free.mkv.log)here is an updated log with a new version installed :)

**Comment by donmelton** [comment]
@ste2w Thanks, but that also appears to be a nightly/developer build: `ffmpeg version N-108614-g37ee36f689-20221011`.

Which website are you downloading from?

Try this website:

https://www.gyan.dev/ffmpeg/builds/

..and look for the "release builds" section:

This link should work for you:

https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z

**Comment by donmelton** [comment]
@ste2w Nevermind. I see the problem. Something changed in a recent release of `ffmpeg` that's no longer mapping audio channels correctly by default when the input has more than 6 channels. I'll take it from here. Stay tuned...

**Comment by ste2w** [comment]
oh! alright i just got it installed thanks for the help btw! :)

**Comment by donmelton** [comment]
I think the change happened in version 5.1. Trying to narrow it down...

**Comment by ste2w** [comment]
if there is anything i can do to help just let me know :)

**Comment by donmelton** [comment]
@ste2w Thanks! I may have you test a fix once I have a patch ready. Stay tuned...

**Comment by ste2w** [comment]
yeah sure will do! :)

**Comment by donmelton** [comment]
@ste2w OK, I have a patch. I'm just doing some more testing before I check it in...

**Comment by ste2w** [comment]
ready when ever you are :) how do i install patches is it just an update through ruby or is it something i download and then just copy and replace the files??

**Comment by ste2w** [comment]
kinda im new to all of this sorry! ive never done anything like this before so would i load the other-transcode.ro into a command prompt and run the same parameters as normal? as in (other-transcode.ro --hevc --eac3  "Path to movie")

**Comment by donmelton** [comment]
@ste2w Yes. But the file extension needs to be `.rb`, not `.ro`.

**Comment by ste2w** [comment]
oh my bad yeah i have a small screen lol i think i got it running ill post a log and hope i did it right lol thanks again for the help ill update shortly :)

**Comment by ste2w** [comment]
alright here is the log file after the patch :)
[Free.mkv.log](https://github.com/donmelton/other_video_transcoding/files/9761612/Free.mkv.log)

**Comment by ste2w** [comment]
it looks like it worked thank you again ill go ahead and close this out! have a great night! :D

**Comment by donmelton** [comment]
@ste2w Thanks for testing! I'm re-opening the issue. I'll close it once the fix is released.

**Comment by ste2w** [comment]
im happy to help! glad i could be of some assistance lol and alright sounds good!

**Comment by donmelton** [comment]
@ste2w OK, I have now released the Gem. Just `gem update other_video_transcoding` and you're good to go.

Thanks again for your help!

**Comment by catdroid75** [comment]
THANK YOU. I've been trying to track down what's been causing this, assumed I had screwed up somewhere. All of my encodes that had TrueHD / Atmos tracks were coming out without the LFE. I had started considering just keeping the original track on everything... this is better!

**Comment by donmelton** [comment]
@catdroid75 You are very welcome! Sorry it took over a week to notice that change to FFmpeg. I'm really glad @ste2w gave us the heads up on it.

**Comment by ste2w** [comment]
hey! i didnt know i could comment after this was closed! lol @catdroid75 im glad i wasnt the only one who had this problem i was really confused to dont worry haha and @donmelton im glad i can help out if yall ever need like a beta tester or anything i would  be happy to help in any way i can! i love bein able to help out with stuff like this :) my knowledge is limited i will admit but im open to learning as well :D

**Comment by donmelton** [comment]
@ste2w Thanks! I will keep that in mind, sir. 👍
