### ISSUE TITLE
Different audio types affect FPS

### ISSUE THREAD

**Issue by asheimo** [donmelton/other_video_transcoding#17]
I was working with the Fantastic Four and noticed the frame rate was pretty low so I ran some comparisons:

no options: ~1000fps
--add-audio eng: ~500fps
--main-audio 2: ~750fps
--add-subtitle eng: ~1000fps
--cuvid: ~600fps

information about the mkv file
Audio 1 - A_AC3 eng Surround 5.1
Audio 2 - A_DTS eng Surround 5.1
Audio 3 - A_AC3 spa Stereo
Audio 4 - A_AC3 eng Stereo
Subtitle 1 - S_VOBSUB eng
Subtitle 2 - S_VOSUB spa
Subtitle 3 - S_VOSUB spa
Subtitle 4 - S_TEXT/UTF8 eng

So my question is how is the audio affecting the fps so much differently depending on options? I get the --cuvid can cause things to be slower at times I saw that in the wiki, included in the testing for completeness. Oh, I'm running a GTX1060 3GB, i5-6600K.

**Comment by donmelton** [comment]
@asheimo Good question! Your input is a DVD rip of "Fantastic Four (2005)", right? I suspect the answer is that the hardware video encoder is so fast that you're seeing slowdowns from copying four audio tracks (the `--add-audio eng` version) and transcoding that DTS track (the `--main-audio 2` version).

**Comment by donmelton** [comment]
@asheimo Is this still an open issue for you?

**Comment by asheimo** [comment]
In the context of other-transcode itself no, I'll close. I'll be persuing on my own out of curiosity and perhaps question the hive mind.
