### ISSUE TITLE
Transcode HEVC Source File using VT -- Help Wanted

### ISSUE THREAD

**Issue by mushbuddygoose** [donmelton/other_video_transcoding#170]
I have some m2ts source files that are HEVC and when I run other-transcode it is copying them vs transcoding them -- which is what I want because they are in a very high bit rate and I am trying to get them into the default values. I haven't run into this before because most of my source material is not in HEVC. I think the tool is assuming that if it's HEVC, we dont want to transcode again (normally most of the time) and it copies the video. 

Is there any way to force it to transcode in accordance with the parameters I have set?

Thanks much and have a happy thanksgiving.

**Comment by loshlee** [comment]
It IS what you want? I’m not trying to be extremely obtuse, just moderately so.

LL

**Comment by mushbuddygoose** [comment]
Yes but on review, NVM. It works fine. Not sure what the issue was why it was copying. Closed.

**Comment by donmelton** [comment]
@mushbuddygoose Coolio. Glad it's working now. 👍

**Comment by loshlee** [comment]
Assuming it’s not what you want, have you tried changing the name extension of your input file to “.ts” rather than “.mt2s”?

LL

**Comment by loshlee** [comment]
For what it’s worth (to anybody), “.m2ts” can always be safely changed to “.ts” (afaik).
