### ISSUE TITLE
Does Videotoolbox support 10-Bit?

### ISSUE THREAD

**Issue by Brandonshire** [donmelton/other_video_transcoding#174]
Hi there! I haven't looked at Other_Video_Trandcoding in a bit, but noticed that that the main page currently still indicates that Videotoolbox only uses 8-bit HEVC encoding. But when I look through the changelog there seems to be an update indicating that at some point in 2021 10-Bit was enabled for Videotoolbox, in Big-Sur and later (unless I'm misunderstanding what the changelog is indicating, which I very well might be).

So basically I'm just looking for clarity on what capabilities there are for Videotoolbox encoding on Macs. Can I get 10-Bit encoding? Also does the recent mentions of moving HDR10 metadata to encodes apply to that?

If all of the above is supported it might be time to update the main page? Anyway, thanks for your help! I'm about to get an M2-Pro Mac Mini and would love to be able to use your tools to downsize my UHD disc rips, without losing quality!

**Comment by ttyS0** [comment]
I can't speak to HDR, but I did just verify that `other-transcode --hevc --10-bit` produces a 10-bit output. I'm on Ventura (macOS 13.2) Here's a snip from `mediainfo`:

```
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@Main
Codec ID                                 : V_MPEGH/ISO/HEVC
Bit depth                                : 10 bits
Writing library                          : Lavc59.37.100 hevc_videotoolbox
```

This is on an M1, but I would expect the same with an M2.

On a side note, unless you just really want HEVC, the Apple Silicon CPUs do a great job with `x264` software encoding, and scale well with the more cores you can throw at it. 

Core count isn't going to matter with VideoToolbox, as it just uses the media encoder circuitry. 

Not sure if any of that helps. Just wanted to clarify that current macOS with M1 does indeed produce 10-bit HEVC output via `other-transcode`, if instructed to do so. :)

**Comment by donmelton** [comment]
Thanks, @ttyS0!

@Brandonshire Did Sean answer your questions?

**Comment by donmelton** [comment]
@Brandonshire OK, I will close this now.
