### ISSUE TITLE
Suggestion: Change audio width for additional audio tracks from Stereo to Surround as default

### ISSUE THREAD

**Issue by pat-e** [donmelton/other_video_transcoding#18]
Hi Don,

as I use the software for Multi-language-movies, I always want the main-language my native language, but also keep the original language of the movie (mostly english).
For that, I would prefer if the audio-option "--add-audio" would default the audio width to surround instead of stereo.

The change would be in line 732:

:width => :surround

If this is not an option, I can continue to change this line by myself if there is an update available.

**Comment by donmelton** [comment]
@pat-e There's no need to modify the code or change the defaults to solve this problem. Just simply append "`=surround`" to your option, .e.g.:

```
other-transcode --add-audio eng=surround C:\Rips\Movie.mkv
```

Does that work for you?

**Comment by pat-e** [comment]
@donmelton : Yes, that works .... but I'm lazy ...

and if one change in code can save me multiple times adding this option, I prefer that.

I convert ALL my received / recorded media (so my DVR makes sometimes strange formatted files and transcode-video will "fix" it and make the file 100% compatible with Plex...). 

If it is not wanted on your side, I can 100% understand it and I will just adjust the code on my HDD after it is downloaded (I do the same change with every version I used with "transcode-video").

**Comment by donmelton** [comment]
@pat-e OK, then I guess you'll have to keep modifying the code. :)

I'll close this now.

**Comment by donmelton** [comment]
@pat-e BTW, you have another option instead of modifying the code. You can always create a wrapper script around `other-transcode` to do this. That's essentially what I do with my own batch files since I always include "`--add-subtitle=commentary --add-subtitle auto --add-subtitle eng`" with my commands.
