### ISSUE TITLE
Trouble burning in subtitles from Blu-ray to MP4

### ISSUE THREAD

**Issue by wassilywabbit** [donmelton/other_video_transcoding#180]
I am trying to transcode the Criterion Blu-ray of The Piano to MP4 (so it can be in my TV library on my iPad with all my purchased media), and I am unable to get the subtitles to render. According to VLC, there are 2 subtitle streams in the ripped MKV. Stream 4 only shows English subtitles for (some of) the Maori speech, and Stream 5 shows English subtitles for EVERYTHING (English & Maori) for the entire movie.

This is the command that I started with:

sudo other-transcode --mp4 --vt --crop 22:22:0:0 --main-audio 1 --add-audio 3 --add-subtitle 4 /Volumes/Stuff/DVD\ -\>\ iPod/The\ Piano/THE\ PIANO_t00.mkv

but I have also tried --add-subtitle 5 / --burn-subtitle 4 / --burn-subtitle 5

do I need to add the =forced switch to --add-subtitle?

I'd love to get a handle on the subtitles, as a lot of the movies I want to rip have subtitles.

Please let me know if you need more information.

![The Piano subtitles](https://user-images.githubusercontent.com/36213639/221770533-5d7fc79b-9bec-40be-87b1-4c8c9f85fcfd.png)

**Comment by loshlee** [comment]
I'm not sure this will provide the help you need, but you've specified "--mp4" which should result in the name extension ".mp4" for the output file. Of course, specifying an output file name is not possible for Other_Video_Transcoding, so do you find any recent .mp4 file in the directory where you executed the command? By default on a Mac, the output of the command leaves that file, as well as its accompanying log file, in your home folder. Please include the log file also. It should contain the input file's name followed by ".mp4", followed by  (".log"). Example: "Movie.mp4.log".

When I run the command "gem info other_video_transcoding", I see the following. Yours should probably be similar, in case you need to check that.

"*** LOCAL GEMS ***

other_video_transcoding (0.12.0)
    Author: Don Melton
    Homepage: https://github.com/donmelton/other_video_transcoding
    License: MIT
    Installed at: /opt/homebrew/lib/ruby/gems/3.2.0

    Other tools to transcode videos."

**Comment by donmelton** [comment]
@wassilywabbit The reason you cannot burn any subtitles is because you're using the wrong track numbers to identify them. In the case of this particular video, your subtitle track numbers are not `4` and `5`. Those are the stream numbers. Your subtitle track numbers are simply `1` and `2`.

You can always use the `--scan` option of `other-transcode` to identify the track numbers of all of your streams, like this:

```
other-transcode --scan /path/to/input.mkv
```

That will print out a list of your streams identifying their track numbers and other characteristics.

Does that help?

**Comment by wassilywabbit** [comment]
That seems to have done the trick. I thought I had tried with subtitle track 1, but that might have been with --add-subtitle, which still doesn't work; it generates this error:

[mp4 @ 0x7f853790a940] Could not find tag for codec hdmv_pgs_subtitle in stream #3, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

I think I have a path forward. Thank you so much!

**Comment by donmelton** [comment]
@wassilywabbit You are very welcome! I'll close this now since it appears to be resolved.
