### ISSUE TITLE
Anybody using an Intel Arc GPU with other-transcode?

### ISSUE THREAD

**Issue by sethrichards** [donmelton/other_video_transcoding#186]
Apologies if this is already being discussed; I searched through the issues and couldn't find anything.

Title pretty much says it all. The video encoders on Intel's new Arc GPUs look to be [as good as (or even better than) Nvidia's](https://www.tomshardware.com/news/amd-intel-nvidia-video-encoding-performance-quality-tested), and the low-end A380 card [looks like a bargain](https://www.newegg.com/asrock-arc-a380-a380-cli-6g/p/N82E16814930076?Description=a380&cm_re=a380-_-14-930-076-_-Product) if your primary interest is video encoding and not gaming. Has anybody tried one with these scripts yet? Does it just show up as a quicksync encoder?

I'm pondering grabbing one to throw in my file server for encode tasks, but other-transcode is my main transcoding frontend and I'd like to at least know if I'm breaking new ground first. 🙂

**Comment by donmelton** [comment]
@sethrichards Good questions! Lemme ask the HiveMind™ on my Slack channel...

**Comment by donmelton** [comment]
@sethrichards OK, I asked my collaborators and none of them have an Intel Arc GPU. So none of us have tried it.

But I assume that the `h264_qsv` and `hevc_qsv` encoders in `ffmpeg` work the same way with it. 🤷‍♀️

Does that help?

**Comment by sethrichards** [comment]
Yeah, I think that pretty much answers my question, thanks. If I end up picking one up I can report back. I can either close this ticket or leave it open in case someone else sees it who has one?

**Comment by donmelton** [comment]
@sethrichards Let's leave this open for a week to see if we get any additional comments. Then I'll close it.

Thanks!

**Comment by donmelton** [comment]
Doesn't look like any additional comments. A pity.
