### ISSUE TITLE
Default Audio Selection

### ISSUE THREAD

**Issue by briangoodman** [donmelton/other_video_transcoding#187]
In non-English DVDs the commentary track is sometimes the first audio track and is flagged as default. To ensure that the proper track is processed by the default config in other_video_transcoding, I use MKVtoolnix GUI to move the main track to first audio track and flag it as default.

Does other_video_transcoding select the main track using the default flag or the first audio track? In other words, do I need to both move the track and flag it as default.

Thanks,

Brian

**Comment by donmelton** [comment]
@briangoodman From the `--help` output:

```
    --main-audio TRACK[=WIDTH]
                    select main audio track by number (default: 1)
                      with optional width (default: surround)
```

So, it's always the first audio track. It doesn't matter which track has the default flag set.

I hope that answers your question.

**Comment by briangoodman** [comment]
Don,

Thanks for the quick response. 

I will continue to move the main track into first position using MKVToolnix for the oddball DVDs gui that is a better workflow for me.

Regards,

Brian

P.S. It's hard to understand why DVD producers put the commentary track in first position.
