### ISSUE TITLE
Plans to implement the --no-log option?

### ISSUE THREAD

**Issue by TraiGuzie** [donmelton/other_video_transcoding#19]
This new transcoder is great! Just as good quality as video-transcode but it also retains the timecode track so it can be used to make linkable proxy media for FCPX.

Only thing I miss is the option to not output a log file, any plans to implement that down the road?

**Comment by spiritphyz** [comment]
Don replied to this issue here:
https://github.com/donmelton/other_video_transcoding/issues/15

TLDR: won’t implement because it makes troubleshooting very hard. Instead, `rm *.log` is an easy option.

**Comment by donmelton** [comment]
@TraiGuzie Sorry, I was playing WoW Classic and in a Molten Core raid.

Thank you for using my tools and I'm glad they're working so well for you! But @spiritphyz (thanks!) is correct, there won't be a `--no-log` option. Sorry. You can find the long answer why in issue #15 (which @spiritphyz also nicely referenced).

Any other questions?

**Comment by TraiGuzie** [comment]
Nope that’s it, thanks again for your awesome tools!

**Comment by donmelton** [comment]
@TraiGuzie You are very welcome!
