### ISSUE TITLE
ffprobe install

### ISSUE THREAD

**Issue by rubinjm** [donmelton/other_video_transcoding#2]
I downloaded ffprobe and ran the executable file in Terminal (I think) but this is what I get when I start other-transcode. How do I set up ffprobe correctly?

other-transcode /Volumes/Drobo/DVDs/moviename/VIDEO_TS 
Verifying "ffprobe" availability...
/usr/local/bin/other-transcode: verifying tool availability failed: No such file or directory - ffprobe

**Comment by donmelton** [comment]
@rubinjm My apologies for taking so long to respond but I was on a road trip today.

You will need to make sure that `ffprobe`, `ffmpeg` and `mkvpropedit` are all in a directory listed in your `$PATH` shell variable. You can see the contents of that variable by executing the following command in Terminal.app:

```
echo $PATH
```

...which should give you a colon-separate list of directories. Hopefully, `/usr/local/bin` is in that list. Which it normally is on macOS. And, if so, you can simply move your downloaded copies of `ffprobe`, `ffmpeg` and `mkvpropedit` to `/usr/local/bin` and then `other-transcode` should be able to find all its dependencies.

Did that solve the problem?

**Comment by rubinjm** [comment]
Thanks—that was a quick response!

/usr/local/bin is listed in $PATH. I moved the files into that folder but get the same message. Does there need to be folder in /usr/local/bin for other-transcode? (P.S. This is my 1st time getting into command line stuff like this so pardon my ignorance.)


Verifying "ffprobe" availability...
/usr/local/bin/other-transcode: verifying tool availability failed: No such file or directory - ffprobe

**Comment by donmelton** [comment]
@rubinjm How are you installing `other-transcode`? You need to use the `gem` command to install it like this:

```
gem install other_video_transcoding
```

It's not supposed to be installed manually.

**Comment by rubinjm** [comment]
Yes—that’s how I did it

**Comment by donmelton** [comment]
@rubinjm OK, what happens when you use this command?

```
which ffprobe
```

That should print out the patch to where you installed the tool.

If not, try quitting Terminal.app and relaunching it.

**Comment by donmelton** [comment]
@rubinjm BTW, you put the actual executables (i.e. the tools) in `/usr/local/bin`, right? Can you also do this at the command line and let me know what happens?

```
ls -l /usr/local/bin/ffprobe
ls -l /usr/local/bin/ffmpeg
ls -l /usr/local/bin/mkvpropedit
```

Thanks.

**Comment by tinusn** [comment]
You could also try to run "ffprobe" from your terminal. If it does not run, then its because it is not on your path.
What OS are you using?

**Comment by diane1612** [comment]
Similar issue here: I'm the administrator. When try to install ffprobe I receive the following ERROR:
You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
I have ffmpeg and mkvpropedit in usr/local/bin. 
Thoughts?

**Comment by donmelton** [comment]
@diane1612 I don't understand how you would receive that error when you install `ffprobe`. That would be weird indeed. Can you please place the command you were trying to execute here and include the full console spew you see in Terminal.app as well. Thanks.

Also, it would be helpful to know which version of macOS you're using.

**Comment by diane1612** [comment]
MacOS 10.14.6

gem install ffprobe — I’ve tried several times; same result.

Sadly, I’m not nerdy enough to know what a “console spew” is.

Thanks for the quick response.

**Comment by donmelton** [comment]
@diane1612 The `ffprobe` tool cannot be installed via the `gem` command. It's a separate executable provided from the same place that `ffmpeg` is downloaded from:

https://evermeet.cx/ffmpeg/

You'll find the download button for `ffprobe` just after `ffmpeg`.

My apologies for using the nerdy term "console spew." That just means the error output printed to Terminal.app when a command fails to execute. I'll be more careful with my terminology in the future. Thank you for letting me know. I really appreciate honest users like yourself because you help improve the project and its documentation.

**Comment by diane1612** [comment]
Then this is correct?

Dianes-iMac:~ diane…$ install ffprobe
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Dianes-iMac:~ diane…$

**Comment by donmelton** [comment]
@diane1612 No, you don't use the `install` command either.

And avoid downloading the "snapshot" versions or files in `.7z` format.

It's better to download the official "versioned" releases and those in `.zip` format: Use these links instead:

https://evermeet.cx/ffmpeg/ffmpeg-4.2.2.zip

https://evermeet.cx/ffmpeg/ffprobe-4.2.2.zip

Then decompress them and move both the `ffmpeg` and `ffprobe` executables from your `Downloads` directory to your `bin` directory within Terminal.app with these commands:

```
mv ~/Downloads/ffmpeg /usr/local/bin/
mv ~/Downloads/ffprobe /usr/local/bin/
```

Does that make sense?

**Comment by diane1612** [comment]
Perfect sense. Thank you. ffprobe is in the building.

A decade ago I worked using a limited set of terminal commands in a Unix environment. I'm comfortable in command line but there are so many processes I don't know.

**Comment by donmelton** [comment]
@diane1612 I'm so glad that worked for you!

Yes, the command line environment can be complicated. Fortunately, you're at least comfortable with it. It's still a scary interface for many users.

And I look forward to hearing from you again!

**Comment by donmelton** [comment]
@rubinjm Are you still having a problem with `ffprobe`?

**Comment by diane1612** [comment]
Thank you for checking. Everything is in the right place. I'll transcode a movie at some point today then let you know if I'm confused again. I appreciate all the help.

**Comment by rubinjm** [comment]
All set now—I re-read the instructions and installed everything with Homebrew :)

Is a VIDEO_TS folder useable by other-transcode? If so, it didn’t work for me

---
computer:~ ***$ other-transcode /Volumes/Drobo/DVDs/U2/VIDEO_TS
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Trying "h264_videotoolbox" video encoder...
Scanning media...
/usr/local/bin/other-transcode: scanning media failed: /Volumes/Drobo/DVDs/U2/VIDEO_TS
---

**Comment by donmelton** [comment]
@rubinjm Great! Yeah, I just added the Homebrew instructions yesterday. :)

No, the `other-transcode` tool can't read a `VIDEO_TS` folder because `ffmpeg` doesn't have that capability. You'll need to convert that DVD directory image to a single file for input. I would suggest using MakeMKV for that. See:

https://www.makemkv.com/

If you have no other questions, is it time to close this issue now?

**Comment by rubinjm** [comment]
LOL—I thought I was crazy for missing the Homebrew instructions because that was so easy!!
Please close this. Thanks again for all the help.

**Comment by donmelton** [comment]
@rubinjm You are very welcome and thanks for using my software.

**Comment by diane1612** [comment]
I know this is closed — maybe you'll see it.

Dianes-iMac:/ diane…$ other-transcode /desktop/ratatouille.mkv
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Trying "h264_videotoolbox" video encoder...
Scanning media...
/usr/local/bin/**other-transcode: scanning media failed**: /desktop/ratatouille.mkv
Dianes-iMac:/ diane…$

I must be missing something in the path? Sorry to keep bothering you.

**Comment by donmelton** [comment]
@diane1612 Oh, I saw it! :) And, no, you're not bothering me at all.

And I'm sorry that you encountered this problem. OK, can you try this command and paste the output here?

```
other-transcode --debug /desktop/ratatouille.mkv
```

That will show me what's really going on behind the scenes. Thanks!

**Comment by diane1612** [comment]
Dianes-iMac:/ diane…$ other-transcode --debug /desktop/ratatouille.mkv
Verifying "ffprobe" availability...
ffprobe version 4.2.2-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2007-2019 the FFmpeg developers
built with Apple clang version 11.0.0 (clang-1100.0.33.16)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
Verifying "ffmpeg" availability...
ffmpeg version 4.2.2-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
built with Apple clang version 11.0.0 (clang-1100.0.33.16)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
Verifying "mkvpropedit" availability...
mkvpropedit v40.0.0 ('Old Town Road + Pony') 64-bit
Finding encoders...
Encoders:
 V..... = Video
 A..... = Audio
 S..... = Subtitle
 .F.... = Frame-level multithreading
 ..S... = Slice-level multithreading
 ...X.. = Codec is experimental
 ....B. = Supports draw_horiz_band
 .....D = Supports direct rendering method 1
 ------
 V..... a64multi             Multicolor charset for Commodore 64 (codec a64_multi)
 V..... a64multi5            Multicolor charset for Commodore 64, extended with 5th color (colram) (codec a64_multi5)
 V..... alias_pix            Alias/Wavefront PIX image
 V..... amv                  AMV Video
 V..... apng                 APNG (Animated Portable Network Graphics) image
 V..... asv1                 ASUS V1
 V..... asv2                 ASUS V2
 V..X.. libaom-av1           libaom AV1 (codec av1)
 V..... avrp                 Avid 1:1 10-bit RGB Packer
 V..X.. avui                 Avid Meridien Uncompressed
 V..... ayuv                 Uncompressed packed MS 4:4:4:4
 V..... bmp                  BMP (Windows and OS/2 bitmap)
 V..... libxavs              libxavs Chinese AVS (Audio Video Standard) (codec cavs)
 V..... cinepak              Cinepak
 V..... cljr                 Cirrus Logic AccuPak
 V.S... vc2                  SMPTE VC-2 (codec dirac)
 VFS... dnxhd                VC3/DNxHD
 V..... dpx                  DPX (Digital Picture Exchange) image
 VFS... dvvideo              DV (Digital Video)
 V.S... ffv1                 FFmpeg video codec #1
 VF.... ffvhuff              Huffyuv FFmpeg variant
 V..... fits                 Flexible Image Transport System
 V..... flashsv              Flash Screen Video
 V..... flashsv2             Flash Screen Video Version 2
 V..... flv                  FLV / Sorenson Spark / Sorenson H.263 (Flash Video) (codec flv1)
 V..... gif                  GIF (Graphics Interchange Format)
 V..... h261                 H.261
 V..... h263                 H.263 / H.263-1996
 V.S... h263p                H.263+ / H.263-1998 / H.263 version 2
 V..... libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V..... libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
 V..... libopenh264          OpenH264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V..... h264_videotoolbox    VideoToolbox H.264 Encoder (codec h264)
 V..... hap                  Vidvox Hap
 V..... libx265              libx265 H.265 / HEVC (codec hevc)
 V..... hevc_videotoolbox    VideoToolbox H.265 Encoder (codec hevc)
 VF.... huffyuv              Huffyuv / HuffYUV
 V..... jpeg2000             JPEG 2000
 VF.... libopenjpeg          OpenJPEG JPEG 2000 (codec jpeg2000)
 VF.... jpegls               JPEG-LS
 VF.... ljpeg                Lossless JPEG
 VF.... magicyuv             MagicYUV video
 VFS... mjpeg                MJPEG (Motion JPEG)
 V.S... mpeg1video           MPEG-1 video
 V.S... mpeg2video           MPEG-2 video
 V.S... mpeg4                MPEG-4 part 2
 V..... libxvid              libxvidcore MPEG-4 part 2 (codec mpeg4)
 V..... msmpeg4v2            MPEG-4 part 2 Microsoft variant version 2
 V..... msmpeg4              MPEG-4 part 2 Microsoft variant version 3 (codec msmpeg4v3)
 V..... msvideo1             Microsoft Video-1
 V..... pam                  PAM (Portable AnyMap) image
 V..... pbm                  PBM (Portable BitMap) image
 V..... pcx                  PC Paintbrush PCX image
 V..... pgm                  PGM (Portable GrayMap) image
 V..... pgmyuv               PGMYUV (Portable GrayMap YUV) image
 VF.... png                  PNG (Portable Network Graphics) image
 V..... ppm                  PPM (Portable PixelMap) image
 VF.... prores               Apple ProRes
 VF.... prores_aw            Apple ProRes (codec prores)
 VFS... prores_ks            Apple ProRes (iCodec Pro) (codec prores)
 V..... qtrle                QuickTime Animation (RLE) video
 V..... r10k                 AJA Kona 10-bit RGB Codec
 V..... r210                 Uncompressed RGB 10-bit
 V..... rawvideo             raw video
 V..... roqvideo             id RoQ video (codec roq)
 V..... rv10                 RealVideo 1.0
 V..... rv20                 RealVideo 2.0
 V..... sgi                  SGI image
 V..... snow                 Snow
 V..... sunrast              Sun Rasterfile image
 V..... svq1                 Sorenson Vector Quantizer 1 / Sorenson Video 1 / SVQ1
 V..... targa                Truevision Targa image
 V..... libtheora            libtheora Theora (codec theora)
 VF.... tiff                 TIFF image
 VF.... utvideo              Ut Video
 V..... v210                 Uncompressed 4:2:2 10-bit
 V..... v308                 Uncompressed packed 4:4:4
 V..... v408                 Uncompressed packed QT 4:4:4:4
 V..... v410                 Uncompressed 4:4:4 10-bit
 V..... libvpx               libvpx VP8 (codec vp8)
 V..... libvpx-vp9           libvpx VP9 (codec vp9)
 V..... libwebp              libwebp WebP image (codec webp)
 V..... wmv1                 Windows Media Video 7
 V..... wmv2                 Windows Media Video 8
 V..... wrapped_avframe      AVFrame to AVPacket passthrough
 V..... xbm                  XBM (X BitMap) image
 V..... xface                X-face image
 V..... xwd                  XWD (X Window Dump) image
 V..... y41p                 Uncompressed YUV 4:1:1 12-bit
 V..... yuv4                 Uncompressed packed 4:2:0
 VF.... zlib                 LCL (LossLess Codec Library) ZLIB
 V..... zmbv                 Zip Motion Blocks Video
 A..... aac                  AAC (Advanced Audio Coding)
 A....D aac_at               aac (AudioToolbox) (codec aac)
 A..... ac3                  ATSC A/52A (AC-3)
 A..... ac3_fixed            ATSC A/52A (AC-3) (codec ac3)
 A..... adpcm_adx            SEGA CRI ADX ADPCM
 A..... g722                 G.722 ADPCM (codec adpcm_g722)
 A..... g726                 G.726 ADPCM (codec adpcm_g726)
 A..... g726le               G.726 little endian ADPCM ("right-justified") (codec adpcm_g726le)
 A..... adpcm_ima_qt         ADPCM IMA QuickTime
 A..... adpcm_ima_wav        ADPCM IMA WAV
 A..... adpcm_ms             ADPCM Microsoft
 A..... adpcm_swf            ADPCM Shockwave Flash
 A..... adpcm_yamaha         ADPCM Yamaha
 A..... alac                 ALAC (Apple Lossless Audio Codec)
 A....D alac_at              alac (AudioToolbox) (codec alac)
 A..... libopencore_amrnb    OpenCORE AMR-NB (Adaptive Multi-Rate Narrow-Band) (codec amr_nb)
 A..... libvo_amrwbenc       Android VisualOn AMR-WB (Adaptive Multi-Rate Wide-Band) (codec amr_wb)
 A..... aptx                 aptX (Audio Processing Technology for Bluetooth)
 A..... aptx_hd              aptX HD (Audio Processing Technology for Bluetooth)
 A..... comfortnoise         RFC 3389 comfort noise generator
 A..X.. dca                  DCA (DTS Coherent Acoustics) (codec dts)
 A..... eac3                 ATSC A/52 E-AC-3
 A..... flac                 FLAC (Free Lossless Audio Codec)
 A..... g723_1               G.723.1
 A..... libgsm               libgsm GSM (codec gsm)
 A..... libgsm_ms            libgsm GSM Microsoft variant (codec gsm_ms)
 A....D ilbc_at              ilbc (AudioToolbox) (codec ilbc)
 A..X.. mlp                  MLP (Meridian Lossless Packing)
 A..... mp2                  MP2 (MPEG audio layer 2)
 A..... mp2fixed             MP2 fixed point (MPEG audio layer 2) (codec mp2)
 A..... libtwolame           libtwolame MP2 (MPEG audio layer 2) (codec mp2)
 A..... libmp3lame           libmp3lame MP3 (MPEG audio layer 3) (codec mp3)
 A..... libshine             libshine MP3 (MPEG audio layer 3) (codec mp3)
 A..... nellymoser           Nellymoser Asao
 A..X.. opus                 Opus
 A..... libopus              libopus Opus (codec opus)
 A..... pcm_alaw             PCM A-law / G.711 A-law
 A....D pcm_alaw_at          pcm_alaw (AudioToolbox) (codec pcm_alaw)
 A..... pcm_dvd              PCM signed 16|20|24-bit big-endian for DVD media
 A..... pcm_f32be            PCM 32-bit floating point big-endian
 A..... pcm_f32le            PCM 32-bit floating point little-endian
 A..... pcm_f64be            PCM 64-bit floating point big-endian
 A..... pcm_f64le            PCM 64-bit floating point little-endian
 A..... pcm_mulaw            PCM mu-law / G.711 mu-law
 A....D pcm_mulaw_at         pcm_mulaw (AudioToolbox) (codec pcm_mulaw)
 A..... pcm_s16be            PCM signed 16-bit big-endian
 A..... pcm_s16be_planar     PCM signed 16-bit big-endian planar
 A..... pcm_s16le            PCM signed 16-bit little-endian
 A..... pcm_s16le_planar     PCM signed 16-bit little-endian planar
 A..... pcm_s24be            PCM signed 24-bit big-endian
 A..... pcm_s24daud          PCM D-Cinema audio signed 24-bit
 A..... pcm_s24le            PCM signed 24-bit little-endian
 A..... pcm_s24le_planar     PCM signed 24-bit little-endian planar
 A..... pcm_s32be            PCM signed 32-bit big-endian
 A..... pcm_s32le            PCM signed 32-bit little-endian
 A..... pcm_s32le_planar     PCM signed 32-bit little-endian planar
 A..... pcm_s64be            PCM signed 64-bit big-endian
 A..... pcm_s64le            PCM signed 64-bit little-endian
 A..... pcm_s8               PCM signed 8-bit
 A..... pcm_s8_planar        PCM signed 8-bit planar
 A..... pcm_u16be            PCM unsigned 16-bit big-endian
 A..... pcm_u16le            PCM unsigned 16-bit little-endian
 A..... pcm_u24be            PCM unsigned 24-bit big-endian
 A..... pcm_u24le            PCM unsigned 24-bit little-endian
 A..... pcm_u32be            PCM unsigned 32-bit big-endian
 A..... pcm_u32le            PCM unsigned 32-bit little-endian
 A..... pcm_u8               PCM unsigned 8-bit
 A..... pcm_vidc             PCM Archimedes VIDC
 A..... real_144             RealAudio 1.0 (14.4K) (codec ra_144)
 A..... roq_dpcm             id RoQ DPCM
 A..X.. s302m                SMPTE 302M
 A..... sbc                  SBC (low-complexity subband codec)
 A..X.. sonic                Sonic
 A..X.. sonicls              Sonic lossless
 A..... libspeex             libspeex Speex (codec speex)
 A..X.. truehd               TrueHD
 A..... tta                  TTA (True Audio)
 A..X.. vorbis               Vorbis
 A..... libvorbis            libvorbis (codec vorbis)
 A..... wavpack              WavPack
 A..... libwavpack            (codec wavpack)
 A..... wmav1                Windows Media Audio 1
 A..... wmav2                Windows Media Audio 2
 S..... ssa                  ASS (Advanced SubStation Alpha) subtitle (codec ass)
 S..... ass                  ASS (Advanced SubStation Alpha) subtitle
 S..... dvbsub               DVB subtitles (codec dvb_subtitle)
 S..... dvdsub               DVD subtitles (codec dvd_subtitle)
 S..... mov_text             3GPP Timed Text subtitle
 S..... srt                  SubRip subtitle (codec subrip)
 S..... subrip               SubRip subtitle
 S..... text                 Raw text subtitle
 S..... webvtt               WebVTT subtitle
 S..... xsub                 DivX subtitles (XSUB)
Trying "h264_videotoolbox" video encoder...
Scanning media...
{

}
/usr/local/bin/other-transcode: scanning media failed: /desktop/ratatouille.mkv
Dianes-iMac:/ diane…$

**Comment by donmelton** [comment]
@diane1612 Thanks! But... dang! The "Scanning media" information failed completely. That is really weird. Does playing the video with `mpv` or VLC.app work?

Also, would you happen to have a copy of MediaInfo installed? It's also a command line tool.

**Comment by diane1612** [comment]
It plays in VLC, not familiar with mpv. I have a copy of MediaInfo now.

**Comment by donmelton** [comment]
@diane1612 It's good that VLC can play it! The `mpv` program is one of those options installs. Don't worry about it for now.

Can you send me the output of what MediaInfo says about your video? Just paste it in here like you did the diagnostic info.

(BTW, my apologies for taking so long to reply. I was eating dinner.)

**Comment by diane1612** [comment]
You’re allowed to eat dinner. And it’s Friday night, for crying out loud. Promise me you have an adult beverage at hand.

Is this what you’re expecting?


General
Unique ID                                : 77072647751413658946292075966791091910 (0x39FBA6EAC47214DA33BFFFB333CB06C6)
Complete name                            : /Users/dianetorrance/Desktop/ratatouille.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 5.10 GiB
Duration                                 : 1h 51mn
Overall bit rate mode                    : Variable
Overall bit rate                         : 6 579 Kbps
Encoded date                             : UTC 2020-01-03 23:06:14
Writing application                      : MakeMKV v1.14.7 darwin(x64-release)
Writing library                          : libmakemkv v1.14.7 (1.3.5/1.4.7) darwin(x64-release)

Video
ID                                       : 1
ID in the original source medium         : 224 (0xE0)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 1h 51mn
Bit rate mode                            : Variable
Bit rate                                 : 6 126 Kbps
Maximum bit rate                         : 9 800 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 23.976 fps
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Scan order                               : 2:3 Pulldown
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.739
Time code of first frame                 : 00:59:59:00
Time code source                         : Group of pictures header
Stream size                              : 4.75 GiB (93%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color primaries                          : BT.601 NTSC
Transfer characteristics                 : BT.601
Matrix coefficients                      : BT.601
Original source medium                   : DVD-Video

Audio
ID                                       : 2
ID in the original source medium         : 189 (0xBD)128 (0x80)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1h 51mn
Bit rate mode                            : Constant
Bit rate                                 : 448 Kbps
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 356 MiB (7%)
Title                                    : Surround 5.1
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
Original source medium                   : DVD-Video

Menu
00:00:00.000                             : en:Chapter 01
00:01:16.242                             : en:Chapter 02
00:06:29.422                             : en:Chapter 03
00:09:22.895                             : en:Chapter 04
00:10:58.190                             : en:Chapter 05
00:13:30.976                             : en:Chapter 06
00:17:40.225                             : en:Chapter 07
00:19:37.543                             : en:Chapter 08
00:24:48.320                             : en:Chapter 09
00:28:55.233                             : en:Chapter 10
00:33:05.183                             : en:Chapter 11
00:38:13.624                             : en:Chapter 12
00:40:33.130                             : en:Chapter 13
00:44:11.348                             : en:Chapter 14
00:46:59.316                             : en:Chapter 15
00:51:27.784                             : en:Chapter 16
00:57:02.285                             : en:Chapter 17
00:59:32.435                             : en:Chapter 18
01:00:53.516                             : en:Chapter 19
01:07:19.735                             : en:Chapter 20
01:11:25.648                             : en:Chapter 21
01:15:28.223                             : en:Chapter 22
01:19:25.093                             : en:Chapter 23
01:23:30.338                             : en:Chapter 24
01:25:34.462                             : en:Chapter 25
01:28:18.326                             : en:Chapter 26
01:32:39.220                             : en:Chapter 27
01:35:41.435                             : en:Chapter 28
01:38:49.924                             : en:Chapter 29
01:40:54.715                             : en:Chapter 30
01:42:59.006                             : en:Chapter 31

**Comment by donmelton** [comment]
@diane1612 LOL! Yes, I had a lovely Pinot handy. :) 

And that is exactly what I was expecting! I take it you ripped this from the "Ratatouille (2007)" DVD? Likely the U.S. version and using MakeMKV to do it?

But there's nothing in that information that looks odd, wrong or menacing.

The good news is that I think I figured out what's wrong anyway! And we can probably thank that Pinot for mellowing me out to notice it. :)

I think you have a problem with your input pathname. You're typing this, right?

```
other-transcode /desktop/ratatouille.mkv
```

When I think you should be typing this:

```
other-transcode ~/desktop/ratatouille.mkv
```

Notice that little tidle at the front of the pathname? Does inserting that fix the problem?

**Comment by donmelton** [comment]
@diane1612 Or do you actually have a `desktop` directory in your root folder?

**Comment by diane1612** [comment]
I’m consuming a mediocre Spanish red. You win.

I opened another instance of Terminal and Voilà! it’s working!! I expect this will take some time and when it’s done I’ll need to figure where the file went, but I’m a happy camper tonight. Thank you so very much. Now I’ll have quality entertainment when I get on the big silver bird heading for the land of great Pinots.

**Comment by donmelton** [comment]
@diane1612 Hey, as long as it works! And Spanish red is just fine with me. :) 

You are very welcome and I look forward to hearing from you again. Feel free to open a new issue when you need to ask a question.

**Comment by diane1612** [comment]
Dianes-iMac:desktop diane…$ 

Looks like I do.

**Comment by diane1612** [comment]
I’m glad Jason put the link on SixColors. I needed to stretch my knowledge and with the next newb you’ll be able to shortcut the process. Have a great weekend!

**Comment by donmelton** [comment]
@diane1612 Jason is a mensch. :) You too! Enjoy your weekend and whatever other wine you decide to imbibe. Happy transcoding!

**Comment by diane1612** [comment]
> Jason is a mensch.

Indeed.
