### ISSUE TITLE
Custom Audio Formats And Track Names

### ISSUE THREAD

**Issue by 69dragons** [donmelton/other_video_transcoding#24]
Will the ability to pick audio formats and add custom track names ever be added? 

I like to have both AAC Stereo and AC3 Surround for my main audio, and AAC Stereo for any remaining audio tracks. Also, I usually rename the non-main audio tracks with descriptive names like:
    Directors Commentary
    Crew Commentary Crew Member1, Crew Member2, etc
    Descriptive Audio

**Comment by donmelton** [comment]
@69dragons Thank you for your question.

You can already choose between DD+, AC-3 and AAC audio formats. You can also pass through audio in other formats. The built-in documentation explains how to do that. You can access the complete documentation like this:

```
other-transcode --help full
```

It's also possible to duplicate your main audio track, i.e. have a surround version and a stereo version of the same audio. The wiki explains how to do that here:

https://github.com/donmelton/other_video_transcoding/wiki/Audio

That page says:

> ...it's possible to duplicate an audio track in a different width. For example, to duplicate the main audio track in stereo format:
> 
> `other-transcode --add-audio 1=stereo C:\Rips\Movie.mkv`
> 
> However, if the main audio track is already in stereo format, it won't be duplicated.

As for descriptive names, my advice is to name the tracks in your original rips. That's what I do. That way I can use the `--add-audio` option to add tracks by name like this:

```
other-transcode --add-audio commentary C:\Rips\Movie.mkv
```

The  title comparison search is case-insensitive, so the example I gave would match both "Directors Commentary" and "Cast Commentary". Plus, the name is always copied to the output for any audio track added by name.

The names of subtitles tracks are always copied to the output no matter how they're added.

I hope that answers your question.

**Comment by 69dragons** [comment]
I do not see an option in --help full for AAC. However, I will check out the page you suggest.

Thanks again.

**Comment by donmelton** [comment]
@69dragons When a track has a `stereo` width, then that track is, by default, in AAC format if it needs to be transcoded. However, if that track is at or below the current stereo bitrate and it's in AC-3 format, then that track is, by default, copied. Why do I do this? Well, it's not a good idea to transcode audio if you don't need to do so. It's especially not a good idea to transcode audio to a higher bitrate.

**Comment by 69dragons** [comment]
I see, the track in question is an AC3 Stereo with a bit rate of 192kbps, it would have been transcoded if its bitrate was over 256kbps then.

Thank you for the clarification.

**Comment by asheimo** [comment]
If you name your tracks ahead of time, either at rip or after with `mkvpropedit` then when you use `other-transcode` you can use the `--copy-track-names` to have them copied over without having to use `--add-audio <name>` you can stick with `--add-audio <#>`. Hope this helps.

**Comment by 69dragons** [comment]
I have had some sleep and got my thoughts together and will try to clarify my position here.

Thank you asheimo, that is good advice. I am surprised I did not think of that myself because that will save me a lot of confusion in the future with my makemkv rips.

The details that I forgot because I was a little tired last night were many fold. Please allow me to clarify what it is I like in an output file and why. I realize this is a holdover from the transcode-video project, but I have some equipment limitations that make this appealing.

output file organization:
    Main Video Track (possibly with burned forced subtitles (ala Star Wars, Kill Bill, etc.))
    Main Audio Track AAC DRC=4
    Main Audio Track AC3 COPIED
    Commentary Audio Track(s) AAC DRC=4
    Descriptive Audio Track(s) AAC DRC=4
    Remaining Subtitle(s)

Starting with the video and subtitle tracks I like this because on initial and subsequent viewings I do not have to remember which subtitle track is the alternate languages only and which is english plus alternate languages. I prefer this organization for audio tracks because on my initial viewing I get the less compressed original track, or in the case of Blu-Ray a less compressed track. On subsequent viewings, or for viewing with headphones or ear buds the AAC with compression is preferable, at least with my equipment. My ears are not what they used to be; and this is usually for long trips with road noise and such. You the usual problem, turn it up to hear the whispers, then the explosions make your ears ring type thing.

So for my use it wold appear, for my use case, a wrapper script (I'll do some more research here as I'm not exactly sure what this is) that calls other-transcode --main-audio 0 --dry-run /path/to/in/file.mkv should give me the ffmpeg command line to get the video compressed well, and I can process the audio and subtitles in my wrapper.

I like the transcode-video (and by extension HandbrakeCLI) always handled the video, but always had frustrations with how it handled the audio and subtitles. I think this new workflow will streamline my process.

Thank again asheimo, and Don I really appreciate it.

**Comment by TehMaster** [comment]
Hey @donmelton  - I almost opened a new issue, but thought this info supports this thread. Is there a way to do either aac or eac3 7.1 (8ch) audio? With transcode-video i had the option to pass the handbrake audio options, but cannot sort out how to do that in this situation.
