### ISSUE TITLE
Playback issues in Plex on Apple TV

### ISSUE THREAD

**Issue by kgarner** [donmelton/other_video_transcoding#32]
I've got a strange issue going on. I run the conversions on a PC using the AMD VCE (the Intel chip doesn't support Quick Sync). The files are then loaded onto a Plex server running on a WD NAS. Everything is fine if I play back on my Roku, or Vizio Plex app, but if I play it on my Apple TV, the video starts playing, but there's no audio. If I pause for a while (45 seconds or longer, not entirely sure how long I have to wait, but it's longer than 30 seconds) then the audio plays fine when I resume. I also noticed that the Apple TV takes longer to start playing than the other players as well (30 seconds vs about 5). Any ideas?

**Comment by donmelton** [comment]
@donmelton I would guess that your Plex server is re-transcoding either the audio or the video for playback on your Apple TV. Have you checked the Dashboard on your Plex server to see if that's the case?

Also, what generation is your Apple TV?

**Comment by vasuvasu** [comment]
@kgarner see if you have a "Enhanced Player" option in the Plex app on appletv. Even my 2015 AppleTV (the first tvOS one, but not the later 4K one) can play back 1080p HEVC content even though that older box doesn't officially support HEVC content.

**Comment by kgarner** [comment]
Sorry for the radio silence. I think the issue was due somehow to the videos being encoded using the AMD VCE hardware acceleration, but the playback happening on a NAS with an Intel chip and no GPU. I upgraded the processor to an Intel with Quick Sync Video capability and re-encoded the files and the playback works fine. No delay and the audio starts right at the beginning of playback.

**Comment by donmelton** [comment]
@kgarner My apologies for not replying sooner. For some strange reason I didn't get the GitHub notification of your comment.

So has your upgrade (and congratulations on that) essentially resolved this issue?

**Comment by kgarner** [comment]
Yes. I no longer have the long delay on start or the missing audio. Everything plays as expected on my Apple TV and my Roku.
