### ISSUE TITLE
output file already exists error

### ISSUE THREAD

**Issue by hubertron** [donmelton/other_video_transcoding#34]
First of all thank you for your fantastic documentation. I am a mac guy by trade but have a nice Windows PC for gaming and the install steps have been great for a newer to windows guy like myself.

I got everything installed just fine but when I try to run a transcode operation on any file I get this error: 

`C:/Ruby26-x64/bin/other-transcode: output file already exists: Angels and Demons_t01.mkv`

I am using this command:

`other-transcode --add-subtitle auto --hevc --nvenc-temporal-aq 'D:\Movies\SomeMovie.mkv'`

Naturally the source file exists, so I am not sure what I am doing wrong, any ideas?

**Comment by hubertron** [comment]
I verified I am getting the same issue if I try h264, if I drop the subtitles, etc. Every iteration of the command gives me that error.

**Comment by donmelton** [comment]
@hubertron You are very welcome for the documentation, sir.

I think the problem you're having is that your current working directory, i.e. the directory shown in your PowerShell command line prompt, is the same directory that your input file is in. Simply `cd` to a different directory and you shouldn't have a problem.

Just to be really clear about this, the `other-transcode` tool will always create its output in your current working directory. So if you have a file with the same name as the output in that directory, then `other-transcode` will fail with the error that you're seeing.

Does that help?

**Comment by hubertron** [comment]
Silly enough that was it. 

I was expect to just be able do `-o' and name the output file but this just means I can make a working director and save my exports there. A slight change to workflow but much better than using handbrakes CLI. Thank you sir! Do you have tip jar?

**Comment by donmelton** [comment]
@hubertron You are, again, very welcome and there's no tip necessary. It's all part of the service. :)
