### ISSUE TITLE
Scanning Media Failed

### ISSUE THREAD

**Issue by kiltedtenor** [donmelton/other_video_transcoding#36]
Running other-transcode from PowerShell on Windows 10 results in an output of "scanning media failed" and it does not transcode or make a log. Seems like it's setup and installed properly, but it's hard to do any digging without a log. All I have to go on is the error message. I even created a C:\Rips folder and named my MKV Movie.mkv so it stuck to the format and even file path of the example in the description... Any tips?

**Comment by donmelton** [comment]
I'm closing this since the user who filed this issue has deleted their account.

**Comment by donmelton** [comment]
I'm closing this since the user who filed this issue has deleted their account.
