### ISSUE TITLE
Laptop Advice

### ISSUE THREAD

**Issue by platonium** [donmelton/other_video_transcoding#40]
We are considering a new laptop. Budget is $1k, preferably less. Wife will use for work (aka Citrix). I’d like to sneak in better hardware transcoding. Is this the right place for these kinds of questions?

Some of the 2020 AMD laptops seem to offer a good value for performance, but I’d love to hear from the more knowledgeable about any drawbacks or limitations with AMD GPUs and OT before getting something.

Thanks!

**Comment by donmelton** [comment]
@platonium If you want to do hardware-based encoding then I would avoid AMD CPUs in laptops unless you can get a model with an Nvidia GPU card. This is because AMD CPUs and GPUs don't match the quality of hardware encoding produced by Nvidia GPUs and Intel CPUs.

That said, if you're satisfied with software-based encoding, e.g. from the `x264` or `x265` encoders, then an AMD CPU will likely be a bit faster than an Intel CPU.

I've asked my contributors to comment here because they're smarter than I am about configuration issues, so let's leave this open for awhile to see if we get other opinions.

**Comment by martinpickett** [comment]
I would like to add a warning. In the previous generation of Nvidia mobile GPU's the video encoding hardware was removed from the lowest end models. Specifically the Nvidia GeForce MX150 & MX250 have no video encoding hardware. To the best of my knowledge Nvidia have not done the same for the current generation of mobile GPUs. If you are unsure you can check Nvidia's big matrix of GPUs [here](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix).

**Comment by klogg416** [comment]
In my limited testing with AMD GPUs, their quality and performance has been subpar. The CPUs are very, very quick with the software encoders, as Don says, but hardware with newer Nvidia or Intel chips is the clear performance leader.

**Comment by platonium** [comment]
Thank you all so much. This is exactly what i needed to know.

If I could impose a little further, any thoughts on the approx $1k or less laptop space that can run 2 external monitors for Citrix remote work (wife’s need) with an Nvidia GPU to OT (my wish)?

Thanks,
Plato

Sent from my iPhone

On May 31, 2020, at 9:59 AM, Kyle <notifications@github.com> wrote:

﻿

In my limited testing with AMD GPUs, their quality and performance has been subpar. The CPUs are very, very quick with the software encoders, as Don says, but hardware with newer Nvidia or Intel chips is the clear performance leader.

**Comment by donmelton** [comment]
@platonium No idea on that question since I use a macOS laptop. :)

**Comment by platonium** [comment]
Don, given your illustrious history, have no doubt you are Apple all the way! Wish I had the budget.

Current thoughts include:

[Asus TUF A 15 GeForce GTX 1660 Ti ](https://store.asus.com/us/item/202003AM280000008)
[Dell G3 15 GTS 1650, 1650 TI, 1660 TI Max Q](https://www.dell.com/en-us/member/shop/compare?ocs=gn3500edfrs,gn3590dovds,gn5500eesws)

Also, wow, you weren't kidding that the software code ran slooowww. If we could leave the thread open a few more days, I would appreciate it. Will close it by the weekend regardless. Thanks again, everyone!

**Comment by donmelton** [comment]
@platonium I would go for the Asus because it has an Nvidia 1660 card which is significantly better than the 1650 card in the Dell.

**Comment by samhutchins** [comment]
@platonium @donmelton 

With the Dell options:
- The 1650 has last gen (Volta) nvenc, despite being a Turing card
- I'm not sure what version of nvenc the 1650Ti has
- The 1660 and above all have the current version of nvenc (turing)

So if you get a version of the Dell one, make sure it has some variant of a 1660.

**Comment by arikalish** [comment]
This just popped up on my RSS feed. Starts at $1000 with AMD and Intel options, nVidia cards: https://gizmodo.com/hps-redesigned-omen-15-boasts-a-slimmer-chassis-and-sup-1843834848

**Comment by platonium** [comment]
Thank you all, found this article from Notebook check on the [1650 TI](https://www.notebookcheck.net/NVIDIA-GeForce-GTX-1650-Ti-Mobile-GPU-Benchmarks-and-Specs.452628.0.html) which states the 1650 TI doesn't use the Turning NVENC so I'll definitely overweight the 1660.

**Comment by arikalish** [comment]
@platonium Buried in that Gizmodo link is this nugget:

> Alternatively, if the Omen 15's starting price of $1,000 still seems a bit too high, HP is also announcing its **Pavilion Gaming 16 laptop, which starts at $800** for a 10th-gen Core i7 CPU, 12GB of RAM, **GTX 1660 Ti GPU**, and either a 256GB SSD or a 1TB HDD. 

Get the SSD or you'll be limiting the day to day performance for the sake of easily expandable storage space.

**Comment by platonium** [comment]
Thank you so much. I don’t see these options shoppable online yet, but am very excited and appreciate you bringing this to my attention. Price point wise, it’s closer to making the wife happy.

Sent from my iPhone

On Jun 2, 2020, at 1:09 PM, Ari Kalish <notifications@github.com> wrote:

﻿

@platonium<https://github.com/platonium> Buried in that Gizmodo link is this nugget:

Alternatively, if the Omen 15's starting price of $1,000 still seems a bit too high, HP is also announcing its Pavilion Gaming 16 laptop, which starts at $800 for a 10th-gen Core i7 CPU, 12GB of RAM, GTX 1660 Ti GPU, and either a 256GB SSD or a 1TB HDD.

Get the SSD or you'll be limiting the day to day performance for the sake of easily expandable storage space.

**Comment by platonium** [comment]
Thanks again to everyone for their recommendations and assistance. Holding out for the HP since it's a better fit budget wise, and will go with the ASUS if it's delayed.

**Comment by platonium** [comment]
Hi, all, hope you don't mind my reopening briefly. The HP 16 that Arikalish mentioned is up on HP the HP website to spec out. 

The lowest configuration that uses Turring comes with an RTX 2060 and costs more than the ASUS as well as provides less ram and storage. 

Could I get people's opinion on the GTX 1660 TI vs the RTX 2060 Max-Q for transcoding? If the RTX is a lot better, then I think the trade off would be ok as I can up the ram and storage later. 

Thank you so much.

**Comment by klogg416** [comment]
No difference at all between the GTX and RTX for transcoding, as long as both GPUs are using the Turning core, they are perfectly equal. GPU speed differences can push performance a few FPS up or down, but the RTX moniker has no bearing on NVEnc performance.

**Comment by donmelton** [comment]
@klogg416 Well put, sir!

**Comment by platonium** [comment]
Thank you so much!
