### ISSUE TITLE
Old DVD Filter Animation

### ISSUE THREAD

**Issue by platonium** [donmelton/other_video_transcoding#42]
Is there a set of options that works like [--filter comb-detect=permissive](https://github.com/donmelton/video_transcoding/issues/292) did for VT?

I've tried regular OT, --no filters, and --detelecine. 

Regular / --no filters has no horizontal lines, but there are some horizontal panning issues.
--Detelecine seems to fix the horizontal pan, but I get some horizontal lines during faster action sequences. 

Thanks as always for your guidance.

**Comment by donmelton** [comment]
@platonium You can also try to force a frame rate. But, really, those are the only choices.

Can you attach or paste in your `.log` file here for the default run so I can see if there's anything unusual about the command generated or your particular input file.

Thanks.

**Comment by platonium** [comment]
Thanks, I also took another look at the transcodes again. The no filters actually has both the horizontal lines and the shearing sorry about that misinformation earlier - no more attempts at multitasking. 

Original - no horizontal lines and no horizontal shearing when panning.
Regular - no horizontal lines, horizontal shearing when panning.
No filters - horizontal lines and horizontal shearing when panning.
Detelecine - horizontal lines and no horizontal shearing when panning.

[The Tick - s01e01 - idea men - base.mkv.log](https://github.com/donmelton/other_video_transcoding/files/4720515/The.Tick.-.s01e01.-.idea.men.-.base.mkv.log)
[The Tick - s01e01 - idea men - detelecine.mkv.log](https://github.com/donmelton/other_video_transcoding/files/4720516/The.Tick.-.s01e01.-.idea.men.-.detelecine.mkv.log)
[The Tick - s01e01 - idea men - no filters.mkv.log](https://github.com/donmelton/other_video_transcoding/files/4720517/The.Tick.-.s01e01.-.idea.men.-.no.filters.mkv.log)


.

**Comment by donmelton** [comment]
@platonium Thanks for the uploads. Well, I don't see anything out of the ordinary.

Is it possible to upload a fragment of the original somewhere?

**Comment by platonium** [comment]
Thanks, I'm trying to create a snippet using ffmpeg. I think the command should be something like: 
```
ffmpeg -ss 00:02:06.0 -i C:\Video\TIK0NNF1_833D\The Tick - s01e01 - idea men.mkv -c copy -t 00:00:20.0 ticksnip.mkv
```
I'm getting a "C:\Video\TIK0NNF1_833D\The: No such file or directory" error after the ```libpostproc``` line.

Have looked around online, but I'm not sure what I'm doing wrong.

**Comment by platonium** [comment]
Slaps forehead - needed to keep the ``` "" ``` around the paths. Here's a [link](https://app.box.com/s/buantr41eazmnjo7cr0muia8sfs9kssb) to the snip via Box. Thank you so much!

**Comment by donmelton** [comment]
@platonium I'm sorry I took so long to respond. I was a little under the weather.

Thanks for the file! Unfortunately I can't do any test transcodes of it yet because a bug in Homebrew has broken my `other-transcode` setup on my development machine.

Hopefully they'll submit a fix soon so I can get `mkvtoolnix` working again.

**Comment by platonium** [comment]
No worries, Don, hope you are feeling better.

Sent from my iPhone

On Jun 4, 2020, at 4:27 PM, Don Melton <notifications@github.com> wrote:

﻿

@platonium<https://github.com/platonium> I'm sorry I took so long to respond. I was a little under the weather.

Thanks for the file! Unfortunately I can't do any test transcodes of it yet because a bug in Homebrew has broken my other-transcode setup on my development machine.

Hopefully they'll submit a fix soon so I can get mkvtoolnix working again.

**Comment by platonium** [comment]
@donmelton after reading #47, I decided to try ```deinterlace```. It seems to have eliminated the earlier issues, but there's something about the scene that doesn't seem to quite match. Not sure if I'm being overly sensitive or if there's really something going on. Have added a [link ](https://app.box.com/s/zxfzprwm6y36veszis1r7s3basg0ejh8)to the deinterlace snip as well in case someone has time to take a look. Thank you so much.

Original Snip - https://app.box.com/s/buantr41eazmnjo7cr0muia8sfs9kssb
Deinterlace Snip - https://app.box.com/s/zxfzprwm6y36veszis1r7s3basg0ejh8

[ticksnip deinterlace.mkv.log](https://github.com/donmelton/other_video_transcoding/files/4832585/ticksnip.deinterlace.mkv.log)
