### ISSUE TITLE
Ability to Choose Destination file (instead of same directory)

### ISSUE THREAD

**Issue by kingmatusevich** [donmelton/other_video_transcoding#44]
For some contexts, I think having the option to decide where the output file is going to fall is a convenient option and I don't think it would require a lot of work or add complexity. 
Thoughts?

**Comment by donmelton** [comment]
@kingmatusevich You can already decide where your output will go simply by using the `cd` command before you invoke `other-transcode`. Your request is actually a duplicate of issue #9 where I've detailed my reasoning for not implementing this. Sorry.

**Comment by donmelton** [comment]
@kingmatusevich BTW, choosing the output filename isn't feasible either since `other-transcode` can take multiple inputs.
