### ISSUE TITLE
audio track copies instead of transcoding (eac3 384)

### ISSUE THREAD

**Issue by vasuvasu** [donmelton/other_video_transcoding#54]
I have input files that are encoded using eac3 640kbit or higher, and I'd like the output to be eac3 384kbit. 

I used the following command

`other-transcode --hevc --nvenc-temporal-aq --surround-bitrate 384 --eac3 "path/to/media.mkv`

However, when ffmpeg runs it just copies the eac3 track and doesn't convert it down. 

Am I doing this correctly?

> Stream mapping:
> 0 = hevc_nvenc / 6000 Kbps
> 1 = copy
> 2 = subrip
> 3 = subrip / SDH

> `ffmpeg -loglevel error -stats -i C:\media\file.mkv -map 0:0 -c:v hevc_nvenc -pix_fmt:v p010le -b:v 6000k -maxrate:v 18000k -rc:v vbr_hq -spatial_aq:v 1 -temporal_aq:v 1 -color_primaries:v bt709 -color_trc:v bt709 -colorspace:v bt709 -metadata:s:v title= -disposition:v default -map 0:1 -c:a:0 copy -metadata:s:a:0 title= -disposition:a:0 default -map 0:2 -c:s:0 copy -disposition:s:0 0 -map 0:3 -c:s:1 copy -disposition:s:1 0 -metadata:g title= file.mkv`

**Comment by donmelton** [comment]
@vasuvasu Yes, you're doing that correctly. And I'm intentionally preventing you from re-transcoding that DD+ track. That's a feature, not a bug. :)

Why? Well, re-transcoding DD+ and AC-3 degrades quality for very little benefit in reduced file size. So I'm trying to prevent users from doing something that they might not realize degrades quality. However, that new target bitrate, i.e. `384`, will still be applied to lossless tracks.

**Comment by vasuvasu** [comment]
haha, gotcha. For what I'm using `other-transcode` for that's cool :)
