### ISSUE TITLE
7.1 Audio Possible?

### ISSUE THREAD

**Issue by TehMaster** [donmelton/other_video_transcoding#58]
Hey @donmelton - Is there a way to do either aac or eac3 7.1 (8ch) audio? With transcode-video i had the option to pass the handbrake audio options, but cannot sort out how to do that in this situation.

**Comment by donmelton** [comment]
@TehMaster Transcoded audio with 7.1 channels is not possible with the DD+ (`eac3`) encoder from FFmpeg. While 7.1 channels _is_ possible using AAC, such layouts are not widely supported and even when they are they often cause various playback problems.

Sorry.
