### ISSUE TITLE
Force PAR?

### ISSUE THREAD

**Issue by catdroid75** [donmelton/other_video_transcoding#59]
I have some poorly-authored DVDs where the aspect ratio is not properly set.  Is there a way for me to force an aspect ratio (8:9 in this case)?

**Comment by donmelton** [comment]
@catdroid75 The best way to fix this problem is to modify the aspect ratio in your original rips of those DVDs. I suggest using `mkvmerge` and its `--aspect-ratio` option to do that.

Let me know if you need help with the command line.

**Comment by catdroid75** [comment]
You learn something new every day. That did the trick. Thanks so much, Don.

**Comment by donmelton** [comment]
@catdroid75 I'm so glad that worked for you!
