### ISSUE TITLE
Unable to encode with 2070 Super

### ISSUE THREAD

**Issue by catdroid75** [donmelton/other_video_transcoding#60]
After using other-transcode and having success with a tiny 1050ti in a disused small form-factor HP business PC, I decided to buy a better card for the task and throw it in a more powerful box I have sitting here.  The specs:

- Windows 10 Home build 2004
- i5 4670
- 16 GB RAM
- MSI GTX 2070 Super w 8 GB RAM

I've followed the install guide to a T (twice on this box alone, with a full OS wipe in-between just to be sure). NVENC works in Handbrake.  But when I try to use other-transcode, the following error occurs:

> Command line:
> ffmpeg -loglevel error -stats -i "C:\MakeMKV\unwigged and unplugged\Unwigged and Unplugged.mkv" -map 0:0 -filter:v yadif=deint=interlaced,fps=24000/1001 -c:v hevc_nvenc -pix_fmt:v p010le -b:v 1500k -maxrate:v 4500k -rc:v vbr_hq -spatial_aq:v 1 -color_primaries:v smpte170m -color_trc:v bt709 -colorspace:v smpte170m -metadata:s:v title= -disposition:v default -map 0:1 -c:a:0 copy -metadata:s:a:0 title= -disposition:a:0 default -sn -metadata:g title= "Unwigged and Unplugged.mkv"
> Transcoding...
> [hevc_nvenc @ 000001b993598bc0] InitializeEncoder failed: invalid param (8): Preset P1 to P7 not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelayEnable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding and set
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> C:/Ruby26-x64/bin/other-transcode: transcoding failed: Unwigged and Unplugged.mkv

[_ffmpeg_56813_6484.mkv.log](https://github.com/donmelton/other_video_transcoding/files/4996108/_ffmpeg_56813_6484.mkv.log)

Any help would be greatly appreciated.  Thanks!

**Comment by donmelton** [comment]
@catdroid75 I'm sorry you're having this problem. Does the same thing happen for H.264 encoding? And what is your exact command line, i.e. which set of options are you passing to `other-transcode`?

**Comment by catdroid75** [comment]
Thanks for the quick response, Don.
From the command prompt:
other-transcode --hevc --nvenc  "C:\MakeMKV\Godspell\Godspell_t00.mkv" 

(Any and all rips in the MakeMKV folder produce the same error)

I get the same error with 264 encoding (only --nvenc as the argument).

**Comment by donmelton** [comment]
@catdroid75 Hmmmmm, other users with similar Nvidia video cards (i.e. new Turing-based models) are not having this problem so my guess is that something else is going on here.

Also, it seems you're using `ffmpeg version git-2020-07-27-16c2ed4`? Please try again with an official release build. That may be the problem.

Other than that, there may be some configuration issue on your machine that's not allowing FFmpeg to correctly initialize your video card.

Also, I've asked the HiveMind™ for help. I'll let you know if they have any ideas.

**Comment by klogg416** [comment]
@catdroid75 I have three thoughts for you beyond getting on a stable build of FFMPEG. The GPU is an RTX with Turing encoder/decoder, so it is compatible, and it is in the GPU #0 position where it is primary, default, and found.

1. Can you confirm that you are running that command yourself while logged in, and that it isn't being triggered by a job and run as a service in a stateless mode?
2. Are you able to test the GPU in another machine and confirm it works there? Can it be jammed it into the original mini PC and just confirm that it will work and transcode in a machine and Windows install that you have previously had success with?
3. I wonder if the NVEnc/NVDec ASIC on the card is defective. The log shows it is found, identified, the command is built accordingly, then it fails when it tried to initialize the part of the card for encoding. In our experience doing this, support is pretty black and white with little-to-no unexplained failures. Once you have updated drivers and FFMPEG, if it still doesn't work I suspect the GPU is your problem. Trying it in a different machine would be the first thing I try after a stable version of FFMPEG.

Good luck.

**Comment by donmelton** [comment]
@klogg416 Thanks for the ideas! These are all good questions.

**Comment by catdroid75** [comment]
@donmelton and @klogg416 , thanks so much for your suggestions.

I must have gotten lucky with my SFF 1050 ti build by getting a daily git that actually worked. Downloading the stable build seems to have done the job.

Or, at least it probably would have done the job. But, seeing that basic mistake made me second-guess the entire build, so I wiped the box clean and started over.

Third time (and a stable version of ffmpeg)'s the charm!

Kyle, I had the same idea of putting the card in the SFF case, but it would have required a bit of Frankenstein-ing; the SFF only has a 215 watt power supply, so the 2070 would have had to pull from its current system PSU while plugged in.  If the complete OS rebuild didn't do it, that was my next step.

Now, having asked for help twice and having both times the answer having nothing to do with Don's work, I think I'll take my leave for a bit and get to ripping some discs. 😊 

Thanks again!

**Comment by klogg416** [comment]
Good to hear, nice that it was software and not the hardware. It hadn't even occurred to me that the SFF PC might not have the PSU to manage the card, which, in retrospect...

Enjoy the new set up.
