### ISSUE TITLE
Red color pixelation

### ISSUE THREAD

**Issue by vasuvasu** [donmelton/other_video_transcoding#61]
It seems that hevc has lower resolution when dealing with high contrast red parts of the frame, like tail lights on a car / building lights / exit signs / etc. 

I noticed it with handbrake and also nvenc .. even at high bitrates like 15Mbit. 

Are there any encoder parameters to help mitigate this?

**Comment by donmelton** [comment]
@vasuvasu Are you using VLC or a VLC-derived player to preview your video? If so, it has a known HEVC decoding bug, particularly with red-saturated content.

**Comment by vasuvasu** [comment]
@donmelton oh woah! I use IINA which uses mpv for its playback and videotoolbox for decoding. I just tried the file in Quicktime and sure enough, no problem there and looks fantastic. So weird! I'd have thought they'd be identical since videotoolbox is being used for decoding.

**Comment by vasuvasu** [comment]
@donmelton did some googling and basically everyone's pointing the finger at someone else :( 

https://github.com/iina/iina/issues/2255
https://github.com/mpv-player/mpv/issues/6369
https://github.com/iina/iina/issues/2468
https://github.com/iina/iina/issues/2975

The consensus seems to be this is a videotoolbox problem when playing back HEVC 10-bit content, but oddly Quicktime Player is just fine.

**Comment by donmelton** [comment]
@vasuvasu Interesting. Normally `mpv` handles HEVC fine. Even on macOS. Go figure.

VideoToolbox is a black box so god only knows what it's doing. :)

So, can we consider this resolved as far as `other-transcode` is concerned?

**Comment by vasuvasu** [comment]
yessir, thank you!
