### ISSUE TITLE
--nvenc-temporal-aq Question

### ISSUE THREAD

**Issue by TehMaster** [donmelton/other_video_transcoding#63]
Hey @donmelton (or community),

Quick Q on the --nvenc-temporal-aq flag/setting - Can you really tell the difference between an encode where you used the flag and where you did not? Does this really impact quality enough to where i should get and use a 1660TI instead of my p2000? I can get a 1660 for a very decent price, but want to hear that the quality/difference is worth it.

Obviously the goal is to get the best encodes possible. 👍 

Appreciate it as always!

**Comment by ttyS0** [comment]
For my eyes, there's a very slight improvement from the stand point of a little less banding and blocking. Back when I was playing with it, I found some scenes that were problematic no matter what and compared them. The improvement was subtle, but observable to me _when I was looking for it_.

I do my NVENC encoding with a Turing card, so I default to adding the temporal-aq flag. If I didn't, the improvement wouldn't be enough for me to go out and upgrade. Along those same lines, if I had a bunch of non-Turing NEVC encodings, I wouldn't re-encode them _just_ for the temporal-aq improvement. There would need to be some other driver, with temporal-aq just being a nice side benefit. 

Hopefully that helps a little. 😎

**Comment by TehMaster** [comment]
@ttyS0 This was EXACTLY what I needed to hear. Thank you. 👍

**Comment by donmelton** [comment]
@ttyS0 Yes, thank you once again! That's an excellent answer!

@TehMaster Is this issue closable now?

**Comment by TehMaster** [comment]
@donmelton Yup. 👍
