### ISSUE TITLE
DTS-HD Stereo to AC3 Stereo instead of AAC?

### ISSUE THREAD

**Issue by heelphan** [donmelton/other_video_transcoding#64]
Thanks for the script, I'm fully switched to HEVC with a Turing card and loving it!

I have a few movies that have DTS-HD Stereo 2.0 audio.  The default behavior of other_video_transcoding is to convert to AAC.  Wouldn't converting to EAC3 or AC3 be higher quality?  Is it possible?   

I have explored the --help options and tried a few things (like --keep-ac3-stereo) and nothing works to convert DTS-HD 2.0 to AC3 or EAC3 2.0.  

Thanks!

**Comment by donmelton** [comment]
@heelphan I'm glad `other-transcode` is working so well for you! And thanks for using my tools.

It's likely that converting lossless stereo inputs to DD+ (E-AC-3) format would be higher quality than AAC format on non-macOS platforms. And you can easily do that by adding the `--all-eac3` option to your command line.

Does that work for you?

**Comment by heelphan** [comment]
Yes, that works!  Can't believe I didn't think to try that.  Thank you, this can be closed now!

**Comment by donmelton** [comment]
@heelphan No problem. The options are not always obvious.

Closing now.
