### ISSUE TITLE
Can't encode VC-1 bluray

### ISSUE THREAD

**Issue by TheClaus** [donmelton/other_video_transcoding#66]
So I am trying to encode a bluray that is VC-1.  

When I try to encode I am getting the following:
`Auto-detecting crop
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Trying "h264_nvenc" video encoder...
Trying "h264_qsv" video encoder...
Trying "h264_amf" video encoder...
Scanning media...
C:/Ruby26-x64/bin/other-transcode: scanning media failed: C:\Media\Input\Friday.1995.DIRECTORS.CUT.1080p.BluRay.REMUX.mkv --nvenc --hevc --nvenc-temporal-aq --crop auto --add-audio 1 --burn-subtitle auto`

Here is the mediainfo:
[Friday.txt](https://github.com/donmelton/other_video_transcoding/files/5087871/Friday.txt)

I am using a GeForce GTX 1660Ti and updated my drivers to 452.06.

**Comment by donmelton** [comment]
@TheClaus I'm sorry you're having this problem.

Can you paste in the output of your same command but please add `--dry-run` to your command line. Thanks.

**Comment by TheClaus** [comment]
@donmelton same results.

`Auto-detecting crop
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Trying "h264_nvenc" video encoder...
Trying "h264_qsv" video encoder...
Trying "h264_amf" video encoder...
Scanning media...
C:/Ruby26-x64/bin/other-transcode: scanning media failed: C:\Media\Input\Friday.1995.DIRECTORS.CUT.1080p.BluRay.REMUX.mkv --dry-run --nvenc --hevc --nvenc-temporal-aq --crop auto --add-audio 1 --burn-subtitle auto`

**Comment by donmelton** [comment]
@TheClaus I'll be honest and say I'm having a real problem reading that because all of the line endings have been removed and it's wrapped to a single line. So, really, I can't tell what's going on. Sorry.

**Comment by donmelton** [comment]
@TheClaus IOW, I can't determine the sequence without the line endings.

**Comment by donmelton** [comment]
@TheClaus Is this file playable in VLC or `mpv`?

**Comment by donmelton** [comment]
@TheClaus Also, I don't see anything odd in the MediaInfo output you included. Thanks for that!

**Comment by TheClaus** [comment]
Auto-detecting crop
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Trying "h264_nvenc" video encoder...
Trying "h264_qsv" video encoder...
Trying "h264_amf" video encoder...
Scanning media...
C:/Ruby26-x64/bin/other-transcode: scanning media failed: C:\Media\Input\Friday.1995.DIRECTORS.CUT.1080p.BluRay.REMUX.mkv --dry-run --nvenc --hevc --nvenc-temporal-aq --crop auto --add-audio 1 --burn-subtitle auto

**Comment by TheClaus** [comment]
@donmelton sorry about that.  I posted it as it should be.  Also it plays fine in mpv.

**Comment by donmelton** [comment]
@TheClaus Thanks! Much clearer but I'm still stumped because it's trying to find video encoders when you've already clearly specified `--nvenc` on the command line.

So I suspect something is wrong with your environment. Can you correctly encode other videos?

**Comment by TheClaus** [comment]
@donmelton sorry about not getting back to you last night.  I tried a different movie and it works fine.  Not sure why it isn't working.  Hopefully someone else might be able to figure it out.

**Comment by donmelton** [comment]
@TheClaus No worries. Can you attach a `.log` file for one of the movies that encodes fine?

**Comment by TheClaus** [comment]
@donmelton I figured it out.  It couldn't handle the ' in DIRECTOR'S CUT part of the file name.  The file was named Friday.1995.DIRECTOR'S.CUT.1080p.BluRay.REMUX.mkv

I found this out when I manually ran the ffmpeg command line and saw that it added an extra ' into the DIRECTOR'S so it looked like this DIRECTOR''S.  Then I looked back at what other-transcode line looked like and saw that it removed the ' from the file which would cause that error to occur. Once I removed the ' from the filename it encoded like every other.

**Comment by donmelton** [comment]
@TheClaus I'm glad you figure it out! But, just so you know, I have plenty of media filenames with a `'` character in them. If you're using tab completion to type your filenames in Windows PowerShell, these will all be properly escaped.

So, can we close this now?

**Comment by TheClaus** [comment]
@donmelton yeah I will say that it is probably my powershell script not properly escaping.
