### ISSUE TITLE
AC3 stereo higher than 256kbps not transcoding to AAC stereo

### ISSUE THREAD

**Issue by brettpynn** [donmelton/other_video_transcoding#67]
Really like the Other Video Transcoding, the speed increase is awesome, thanks for your work!

I'm trying to transcode a TV show which has AC3 48k stereo at 384kbps. I want is to keep AC3 as the main audio and then add a transcoded AAC stereo for devices that can't do the AC3. It seems like no matter what options I try, the show only sends a passthrough of AC3 stereo. I'll provide a few of my attempts. I'm even OK with just getting an AAC version so it is the most compatible, but I can't seem to get it to do that. I'm unsure if the AC3 vs AAC in this case would really give me much by keeping both. 

![Screen Shot 2020-08-18 at 12 14 18 PM](https://user-images.githubusercontent.com/4935963/90556791-551ec500-e14e-11ea-881f-0ae8c4987f3c.png)

```
other-transcode show.mkv --mp4
other-transcode show.mkv --mp4 --main-audio 1=original --add-audio 1=stereo
other-transcode show.mkv --mp4 --main-audio 1=surround --add-audio 1=stereo
other-transcode show.mkv --mp4 --main-audio 1=stereo --add-audio 1=stereo --stereo-bitrate 256
other-transcode show.mkv --mp4 --main-audio 1=stereo --stereo-bitrate 256
other-transcode show.mkv --mp4 --main-audio 1=stereo --keep-ac3-stereo
```

I'm assuming I have a flag wrong, but the wiki seems to say that if the AC3 stereo is above the 256kbps it should be converted to AAC. Thanks for the help.

**Comment by donmelton** [comment]
@brettpynn Thanks so much for using my tools! I'm sorry you're having this problem. And I wish the solution was a little more obvious but, believe it or not, I intentionally make such scenarios complicated because such configurations are not optimal.

Here's what you need to do:

```
other-transcode show.mkv --mp4 --add-audio 1 --stereo-bitrate 256
```

Where the stereo bitrate is simply lower than the actual bitrate of your original audio.

Does that work for you?

**Comment by brettpynn** [comment]
Thanks for the reply. It didn't work, still AC3. Curious, what do you think the optimal is? To keep AC3 or convert to AAC? I'm open, just thought having both would be best for compatibility or at least just the AAC.

Here is the scan of the MKV:
```
other-transcode show_test.mkv --scan                                  
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Scanning media...
show_test.mkv
      format = mpeg2video / 720 x 480 / 30000/1001 fps / 6997 Kbps
    duration = 00:28:25.12
#1 audio:
      format = ac3 / stereo / 192 Kbps
    language = eng
       title = Stereo
#1 subtitle:
      format = dvd_subtitle / 670 frames
    language = eng
       flags = default
``` 

Here is the command output:
```
other-transcode show_test.mkv --mp4 --add-audio 1 --stereo-bitrate 256
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Trying "h264_videotoolbox" video encoder...
Scanning media...
duration = 00:28:25.12
Stream mapping:
 0 = h264_videotoolbox / 2000 Kbps
 1 = copy
Command line:
ffmpeg -loglevel error -stats -i show_test.mkv -map 0:0 -filter:v yadif\=deint\=interlaced,fps\=24000/1001 -c:v h264_videotoolbox -b:v 2000k -color_primaries:v smpte170m -color_trc:v bt709 -colorspace:v smpte170m -metadata:s:v title\= -disposition:v default -map 0:1 -c:a:0 copy -metadata:s:a:0 title\= -disposition:a:0 default -sn -metadata:g title\= -movflags disable_chpl show_test.mp4
Transcoding...
frame=40882 fps=599 q=-0.0 Lsize=  457106kB time=00:28:25.08 bitrate=2196.1kbits/s speed=  25x    
Assembling `.log` file...
Done.

Elapsed time: 00:01:08
```

Thanks

**Comment by brettpynn** [comment]
So looks like it is on my end, the files I was seeing this issue do have 192kbps ac3. I don't know how I mixed up the scan, but I did. Sorry for that, but your command does work when I run it on my other mkv that has higher than 256 just like the wiki says. 

Still curious your thoughts on whether to keep the ac3 192kbps instead of converting to AAC or having both. 

Thanks and sorry for the mix up. I thought it might have been on my end.

**Comment by donmelton** [comment]
@brettpynn No worries. Just use this command then:

```
other-transcode show.mkv --mp4 --add-audio 1 --stereo-bitrate 191
```

**Comment by donmelton** [comment]
@brettpynn IOW, if that wasn't clear, just set the stereo bitrate below you're actual bitrate.

**Comment by brettpynn** [comment]
Yep, I got it, thanks for the help! I'll close the issue.

**Comment by donmelton** [comment]
@brettpynn No problem! Glad I could help. Don't be shy about asking questions.
