### ISSUE TITLE
Display # of tracks at start?

### ISSUE THREAD

**Issue by vr8hub** [donmelton/other_video_transcoding#7]
The former Best Transcoder on the Planet (BTotP™) showed a running % as it was doing its thing. I realize that was probably a function of the tool being used, and ffmpeg might not have that option. Since we are getting track# updated every so often, I'm wondering if it's possible to display (i.e. is it available?) the total # of tracks at the beginning so we can at least have an idea how far along the transcode is.

**Comment by rhapsodians** [comment]
Hi @vr8hub ... if you're looking to see progress, @donmelton already provides this by including the total duration details plus an ongoing timestamp. I've added an example transcode below:

```Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Scanning media...
duration = 00:42:21.707
Stream mapping:
 0 = hevc_nvenc / 6000 Kbps
 1 = eac3 / 640 Kbps
 1 = aac / 256 Kbps / stereo
 2 = hdmv_pgs_subtitle / English
Command line:
ffmpeg -loglevel error -stats -i "E:\Rips\Movie.mkv" -map 0:0 -c:v hevc_nvenc -pix_fmt:v p010le -b:v 6000k -maxrate:v 18000k -rc:v vbr_hq -spatial_aq:v 1 -temporal_aq:v 1 -color_primaries:v bt709 -color_trc:v bt709 -colorspace:v bt709 -metadata:s:v title= -disposition:v default -map 0:1 -c:a:0 eac3 -b:a:0 640k -metadata:s:a:0 title= -disposition:a:0 default -map 0:1 -c:a:1 aac -b:a:1 256k -ac:a:1 2 -metadata:s:a:1 title= -disposition:a:1 0 -map 0:2 -c:s:0 copy -disposition:s:0 0 -metadata:g title= "The Expanse - S02E09 - The Weeping Somnambulist.mkv"
Transcoding...
frame=39718 fps=131 q=17.0 size= 1402597kB time=00:27:37.28 bitrate=6919.1kbits/s speed=5.46x```

Both "duration" at the start and "time" throughout the transcode should give a good view of what's going on.

**Comment by rhapsodians** [comment]
Both "**duration = 00:42:21.707**" at the start and "**time=00:27:37.28**" throughout the transcode should give a good view of what's going on.

**Comment by vr8hub** [comment]
Wow. I'm going to have to blame this on jet lag. (I told you, it's good for a month.) I saw the frame rate, I saw the bitrate, I somehow skipped over the time. I didn't really believe this until I did another one locally, and … there it is. It's amazing what my eyes sometimes don't see.

I believe the proper term for this is […](https://youtu.be/OjYoNL4g5Vg?t=5)

**Comment by donmelton** [comment]
@vr8hub My apologies for never responding to the two days ago. I somehow never got the notification from GitHub. Yikes! (But I do like that proper term.)

And thanks, @rhapsodians, for doing my work for me, sir!
