### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by platonium** [donmelton/other_video_transcoding#70]
Dear Don,

Thanks for the update and making your tools and critical eye accessible to us. After updating the gem, I also downloaded the latest versions of ffmpeg, ffprove, mkvpropedit and mpv as well. Copying them into the BIN I had set up.

Afterwards, I get this error message. The batch file I was using had worked with the previous version of other-transcode along with the older versions of ffmpeg, etc. Could I ask for your help when convenient?

Thank you so much as always!

[_ffmpeg_49310_10824.mkv.log](https://github.com/donmelton/other_video_transcoding/files/5213597/_ffmpeg_49310_10824.mkv.log)

[hevc_nvenc @ 0000024cf5d09c80] InitializeEncoder failed: invalid param (8): Preset P1 to P7 not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelayEnable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding and set
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

**Comment by donmelton** [comment]
@platonium I'm sorry you're having this problem. But you're using a nightly build of `ffmpeg`. The FFmpeg developers have likely introduced a backward incompatible change due to their integration of a new Nvidia library. Please download a release version of `ffmpeg`, preferably 4.3.1 or 4.3, and that should fix the problem.

**Comment by platonium** [comment]
Dear Don,

Thank you so much. The file name had the term static in it so I thought that was ok. The release version 4.3.1 works great. My bad!

Best,
Plato

**Comment by donmelton** [comment]
@platonium No worries. Thanks for giving me the heads up that the FFmpeg developers are breaking shit again. :)
