### ISSUE TITLE
Link to ffmpeg for Windows in Wiki is Not Working

### ISSUE THREAD

**Issue by hisaac** [donmelton/other_video_transcoding#72]
Just wanted to give you a heads up that the link [here on the wiki](https://github.com/donmelton/other_video_transcoding/wiki/Windows) for where to download ffmpeg for Windows is not working.

The link is https://ffmpeg.zeranoe.com/builds/

I tried installing ffmpeg using [scoop](https://scoop.sh) as well, but it looks like it uses the same source, so it also failed.

Not sure there's really much you can do about it, unless you know of another place to get ffmpeg for Windows?

**Comment by weaverm** [comment]
[https://ffmpeg.org/download.html#build-windows](https://ffmpeg.org/download.html#build-windows) seems to point to two places:
[https://www.gyan.dev/ffmpeg/builds/](https://www.gyan.dev/ffmpeg/builds/)
[https://github.com/BtbN/FFmpeg-Builds/releases](https://github.com/BtbN/FFmpeg-Builds/releases)

The 'release essentials' from gyan.dev seems like it is what you'd be looking for.

**Comment by hisaac** [comment]
Thanks @weaverm, that's what I'll try. The docs should probably be updated too if that previous link is going to be down indefinitely.

**Comment by donmelton** [comment]
@hisaac Thanks for pointing that out! And @weaverm is correct, that's where you should be getting your Windows builds for now.

I'll update the wiki this week.

**Comment by donmelton** [comment]
@hisaac @weaverm I've just updated the link. Sorry that took so long.
