### ISSUE TITLE
Transcoding failed on newer FFmpeg builds

### ISSUE THREAD

**Issue by TehMaster** [donmelton/other_video_transcoding#80]
Hey @donmelton, 

I believe I either found an issue, or missed you saying not to update FFmpeg. It appears on the newer builds (9/30, 9/21, latest) of FFmpeg other_transcode is failing with the below error. Reverting back to the June build of FFmpeg gets things working again.

cmd: other-transcode --hevc --nvenc --eac3 --add-audio commentary* --add-subtitle eng "PATH"

Error:
[hevc_nvenc @ 0000025bfdd913c0] InitializeEncoder failed: invalid param (8): Preset P1 to P7 not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelayEnable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding and set
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
C:/Program Files/Ruby27-x64/bin/other-transcode: transcoding failed:

As always i appreciate the help. Thanks!

**Comment by TheClaus** [comment]
@TehMaster I am using 4.3.1 which was released on 10/1 and it is working fine for me.  Are you using the daily builds or the release builds?

I downloaded the release builds from [here](https://www.gyan.dev/ffmpeg/builds/) and grabbed the ffmpeg-4.3.1-2020-10-01-essentials_build.zip

**Comment by TehMaster** [comment]
Thanks for the reply @TheClaus. That is often the source of where i get my builds as well.

Using the ffmpeg-4.3.1-2020-10-01-essentials_build does indeed work. Strangely I already had this downloaded and it was not working earlier, but i may have made a mistake.

I can re-create the error using ffmpeg-2020-10-28-git-e5be4c5a88-full_build and ffmpeg-2020-10-28-git-e5be4c5a88-essentials_build, so maybe this is something in the newer builds?

Either way i am working again and appreciate the help.
