### ISSUE TITLE
Audio Track Names?

### ISSUE THREAD

**Issue by weaverm** [donmelton/other_video_transcoding#95]
In my experiments, I've noticed that if I add a track by name, the resulting output seems to have that name (more precisely the name in the source MKV is put in the output file if the passed string is contained in a source name).

`other-transcode --x265 --add-audio Commentary /path/to/Movie.mkv`

In this other issue ([https://github.com/donmelton/other_video_transcoding/issues/24#issuecomment-605390861](https://github.com/donmelton/other_video_transcoding/issues/24#issuecomment-605390861)) Don commented…

> The names of subtitles tracks are always copied to the output no matter how they're added.

That has not been my experience. If I do an add-audio by specifying the track number, I find the name is not copied into the output.
`other-transcode --x265 --add-audio 3 /path/to/Movie.mkv`

Is this expected?

**Comment by donmelton** [comment]
@weaverm Yes, that's the expected behavior. My rationale is that if you added it by name then you cared about the name because you probably added that name in your source file, whichis typical for commentary tracks. And I don't want to copy the useless and often misleading names for audio tracks that are automatically assigned by MakeMKV.

Any other questions?

**Comment by weaverm** [comment]
Okay. In the case of audio tracks that have unique names, say, 'Commentary' and 'Score Only' would I want two --add-audio switches that call out each name?

I know in the case of 'Director Commentary' and 'Writer Commentary', for example, a single `--add-audio Commentary` will add both audio tracks.

**Comment by donmelton** [comment]
@weaverm Yes, use as many `--add-audio` options as necessary. I typically use `--add-audio commentary --add-audio SDH` on my command line.

**Comment by weaverm** [comment]
I've learned to use mkvpropedit ([https://mkvtoolnix.download/doc/mkvpropedit.html](https://mkvtoolnix.download/doc/mkvpropedit.html)) lately to fix up old files that weren't properly labeled. Seems like a useful nugget to leave in this issue before closing it.

**Comment by donmelton** [comment]
@weaverm Thanks. And that's exactly what I use on old files.
