### ISSUE TITLE
Transcoding DVD's

### ISSUE THREAD

**Issue by mumblequatch** [donmelton/other_video_transcoding#99]
Unclear how to transcode directly from DVD's (presumably this is possible?)

When I enter the path for my Amélie DVD, which is on an external Blu-Ray drive, I get the following error:

_Scanning media...
/usr/local/bin/other-transcode: scanning media failed: /Volumes/AMELIE_

Is there a step I'm missing?

**Comment by donmelton** [comment]
@mumblequatch The scan is likely failing because your DVD is encrypted. You need to first rip the video from the disc in your Blu-ray drive to your hard disk using a tool like MakeMKV and use the ripped video as input. See: https://www.makemkv.com/

Does that make sense?

**Comment by mumblequatch** [comment]
D'oh. Sure does. Thanks.

**Comment by donmelton** [comment]
@mumblequatch OK, I will close this issue then.
